// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module median_blur_accel_Mat2Axi (
        imgOutput_420_dout,
        imgOutput_420_empty_n,
        imgOutput_420_read,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        dout,
        rows,
        cols,
        ap_clk,
        ap_rst,
        dout_ap_vld,
        rows_ap_vld,
        cols_ap_vld,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [23:0] imgOutput_420_dout;
input   imgOutput_420_empty_n;
output   imgOutput_420_read;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [63:0] m_axi_gmem1_AWADDR;
output  [0:0] m_axi_gmem1_AWID;
output  [31:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [0:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [31:0] m_axi_gmem1_WDATA;
output  [3:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [0:0] m_axi_gmem1_WID;
output  [0:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [63:0] m_axi_gmem1_ARADDR;
output  [0:0] m_axi_gmem1_ARID;
output  [31:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [0:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [31:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [0:0] m_axi_gmem1_RID;
input  [0:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [0:0] m_axi_gmem1_BID;
input  [0:0] m_axi_gmem1_BUSER;
input  [63:0] dout;
input  [31:0] rows;
input  [31:0] cols;
input   ap_clk;
input   ap_rst;
input   dout_ap_vld;
input   rows_ap_vld;
input   cols_ap_vld;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    Mat2Axi_entry28_U0_ap_start;
wire    Mat2Axi_entry28_U0_start_full_n;
wire    Mat2Axi_entry28_U0_ap_done;
wire    Mat2Axi_entry28_U0_ap_continue;
wire    Mat2Axi_entry28_U0_ap_idle;
wire    Mat2Axi_entry28_U0_ap_ready;
wire    Mat2Axi_entry28_U0_start_out;
wire    Mat2Axi_entry28_U0_start_write;
wire   [63:0] Mat2Axi_entry28_U0_dout_out_din;
wire    Mat2Axi_entry28_U0_dout_out_write;
wire   [12:0] Mat2Axi_entry28_U0_rows_out_din;
wire    Mat2Axi_entry28_U0_rows_out_write;
wire   [31:0] Mat2Axi_entry28_U0_rows_out1_din;
wire    Mat2Axi_entry28_U0_rows_out1_write;
wire   [15:0] Mat2Axi_entry28_U0_cols_out_din;
wire    Mat2Axi_entry28_U0_cols_out_write;
wire   [31:0] Mat2Axi_entry28_U0_cols_out2_din;
wire    Mat2Axi_entry28_U0_cols_out2_write;
wire    addrbound_U0_ap_start;
wire    addrbound_U0_ap_done;
wire    addrbound_U0_ap_continue;
wire    addrbound_U0_ap_idle;
wire    addrbound_U0_ap_ready;
wire   [10:0] addrbound_U0_return_r;
wire    addrbound_U0_return_r_ap_vld;
wire    addrbound_U0_rows_read;
wire    addrbound_U0_cols_read;
wire    ap_channel_done_p_channel;
wire    p_channel_full_n;
wire    Mat2Axi_Block_split24_proc_U0_ap_start;
wire    Mat2Axi_Block_split24_proc_U0_ap_done;
wire    Mat2Axi_Block_split24_proc_U0_ap_continue;
wire    Mat2Axi_Block_split24_proc_U0_ap_idle;
wire    Mat2Axi_Block_split24_proc_U0_ap_ready;
wire   [10:0] Mat2Axi_Block_split24_proc_U0_ap_return;
wire    ap_channel_done_axibound_V;
wire    axibound_V_full_n;
wire    Mat2AxiStream_U0_imgOutput_420_read;
wire   [31:0] Mat2AxiStream_U0_ldata1_din;
wire    Mat2AxiStream_U0_ldata1_write;
wire    Mat2AxiStream_U0_rows_read;
wire    Mat2AxiStream_U0_cols_read;
wire    Mat2AxiStream_U0_ap_start;
wire    Mat2AxiStream_U0_ap_done;
wire    Mat2AxiStream_U0_ap_ready;
wire    Mat2AxiStream_U0_ap_idle;
wire    Mat2AxiStream_U0_ap_continue;
wire    AxiStream2Axi_U0_ap_start;
wire    AxiStream2Axi_U0_ap_done;
wire    AxiStream2Axi_U0_ap_continue;
wire    AxiStream2Axi_U0_ap_idle;
wire    AxiStream2Axi_U0_ap_ready;
wire    AxiStream2Axi_U0_ldata1_read;
wire    AxiStream2Axi_U0_m_axi_gmem1_AWVALID;
wire   [63:0] AxiStream2Axi_U0_m_axi_gmem1_AWADDR;
wire   [0:0] AxiStream2Axi_U0_m_axi_gmem1_AWID;
wire   [31:0] AxiStream2Axi_U0_m_axi_gmem1_AWLEN;
wire   [2:0] AxiStream2Axi_U0_m_axi_gmem1_AWSIZE;
wire   [1:0] AxiStream2Axi_U0_m_axi_gmem1_AWBURST;
wire   [1:0] AxiStream2Axi_U0_m_axi_gmem1_AWLOCK;
wire   [3:0] AxiStream2Axi_U0_m_axi_gmem1_AWCACHE;
wire   [2:0] AxiStream2Axi_U0_m_axi_gmem1_AWPROT;
wire   [3:0] AxiStream2Axi_U0_m_axi_gmem1_AWQOS;
wire   [3:0] AxiStream2Axi_U0_m_axi_gmem1_AWREGION;
wire   [0:0] AxiStream2Axi_U0_m_axi_gmem1_AWUSER;
wire    AxiStream2Axi_U0_m_axi_gmem1_WVALID;
wire   [31:0] AxiStream2Axi_U0_m_axi_gmem1_WDATA;
wire   [3:0] AxiStream2Axi_U0_m_axi_gmem1_WSTRB;
wire    AxiStream2Axi_U0_m_axi_gmem1_WLAST;
wire   [0:0] AxiStream2Axi_U0_m_axi_gmem1_WID;
wire   [0:0] AxiStream2Axi_U0_m_axi_gmem1_WUSER;
wire    AxiStream2Axi_U0_m_axi_gmem1_ARVALID;
wire   [63:0] AxiStream2Axi_U0_m_axi_gmem1_ARADDR;
wire   [0:0] AxiStream2Axi_U0_m_axi_gmem1_ARID;
wire   [31:0] AxiStream2Axi_U0_m_axi_gmem1_ARLEN;
wire   [2:0] AxiStream2Axi_U0_m_axi_gmem1_ARSIZE;
wire   [1:0] AxiStream2Axi_U0_m_axi_gmem1_ARBURST;
wire   [1:0] AxiStream2Axi_U0_m_axi_gmem1_ARLOCK;
wire   [3:0] AxiStream2Axi_U0_m_axi_gmem1_ARCACHE;
wire   [2:0] AxiStream2Axi_U0_m_axi_gmem1_ARPROT;
wire   [3:0] AxiStream2Axi_U0_m_axi_gmem1_ARQOS;
wire   [3:0] AxiStream2Axi_U0_m_axi_gmem1_ARREGION;
wire   [0:0] AxiStream2Axi_U0_m_axi_gmem1_ARUSER;
wire    AxiStream2Axi_U0_m_axi_gmem1_RREADY;
wire    AxiStream2Axi_U0_m_axi_gmem1_BREADY;
wire    AxiStream2Axi_U0_dout_read;
wire    ap_sync_continue;
wire    dout_c_full_n;
wire   [63:0] dout_c_dout;
wire    dout_c_empty_n;
wire    rows_c_full_n;
wire   [12:0] rows_c_dout;
wire    rows_c_empty_n;
wire    rows_c11_full_n;
wire   [31:0] rows_c11_dout;
wire    rows_c11_empty_n;
wire    cols_c_full_n;
wire   [15:0] cols_c_dout;
wire    cols_c_empty_n;
wire    cols_c12_full_n;
wire   [31:0] cols_c12_dout;
wire    cols_c12_empty_n;
wire   [10:0] p_channel_dout;
wire    p_channel_empty_n;
wire   [10:0] axibound_V_dout;
wire    axibound_V_empty_n;
wire    ldata_full_n;
wire   [31:0] ldata_dout;
wire    ldata_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_addrbound_U0_din;
wire    start_for_addrbound_U0_full_n;
wire   [0:0] start_for_addrbound_U0_dout;
wire    start_for_addrbound_U0_empty_n;
wire   [0:0] start_for_Mat2AxiStream_U0_din;
wire    start_for_Mat2AxiStream_U0_full_n;
wire   [0:0] start_for_Mat2AxiStream_U0_dout;
wire    start_for_Mat2AxiStream_U0_empty_n;
wire    addrbound_U0_start_full_n;
wire    addrbound_U0_start_write;
wire    Mat2Axi_Block_split24_proc_U0_start_full_n;
wire    Mat2Axi_Block_split24_proc_U0_start_write;
wire    Mat2AxiStream_U0_start_full_n;
wire    Mat2AxiStream_U0_start_write;
wire    AxiStream2Axi_U0_start_full_n;
wire    AxiStream2Axi_U0_start_write;

median_blur_accel_Mat2Axi_entry28 Mat2Axi_entry28_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Mat2Axi_entry28_U0_ap_start),
    .start_full_n(Mat2Axi_entry28_U0_start_full_n),
    .ap_done(Mat2Axi_entry28_U0_ap_done),
    .ap_continue(Mat2Axi_entry28_U0_ap_continue),
    .ap_idle(Mat2Axi_entry28_U0_ap_idle),
    .ap_ready(Mat2Axi_entry28_U0_ap_ready),
    .start_out(Mat2Axi_entry28_U0_start_out),
    .start_write(Mat2Axi_entry28_U0_start_write),
    .dout(dout),
    .rows(rows),
    .cols(cols),
    .dout_out_din(Mat2Axi_entry28_U0_dout_out_din),
    .dout_out_full_n(dout_c_full_n),
    .dout_out_write(Mat2Axi_entry28_U0_dout_out_write),
    .rows_out_din(Mat2Axi_entry28_U0_rows_out_din),
    .rows_out_full_n(rows_c_full_n),
    .rows_out_write(Mat2Axi_entry28_U0_rows_out_write),
    .rows_out1_din(Mat2Axi_entry28_U0_rows_out1_din),
    .rows_out1_full_n(rows_c11_full_n),
    .rows_out1_write(Mat2Axi_entry28_U0_rows_out1_write),
    .cols_out_din(Mat2Axi_entry28_U0_cols_out_din),
    .cols_out_full_n(cols_c_full_n),
    .cols_out_write(Mat2Axi_entry28_U0_cols_out_write),
    .cols_out2_din(Mat2Axi_entry28_U0_cols_out2_din),
    .cols_out2_full_n(cols_c12_full_n),
    .cols_out2_write(Mat2Axi_entry28_U0_cols_out2_write)
);

median_blur_accel_addrbound addrbound_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(addrbound_U0_ap_start),
    .ap_done(addrbound_U0_ap_done),
    .ap_continue(addrbound_U0_ap_continue),
    .ap_idle(addrbound_U0_ap_idle),
    .ap_ready(addrbound_U0_ap_ready),
    .return_r(addrbound_U0_return_r),
    .return_r_ap_vld(addrbound_U0_return_r_ap_vld),
    .rows_dout(rows_c_dout),
    .rows_empty_n(rows_c_empty_n),
    .rows_read(addrbound_U0_rows_read),
    .cols_dout(cols_c_dout),
    .cols_empty_n(cols_c_empty_n),
    .cols_read(addrbound_U0_cols_read)
);

median_blur_accel_Mat2Axi_Block_split24_proc Mat2Axi_Block_split24_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Mat2Axi_Block_split24_proc_U0_ap_start),
    .ap_done(Mat2Axi_Block_split24_proc_U0_ap_done),
    .ap_continue(Mat2Axi_Block_split24_proc_U0_ap_continue),
    .ap_idle(Mat2Axi_Block_split24_proc_U0_ap_idle),
    .ap_ready(Mat2Axi_Block_split24_proc_U0_ap_ready),
    .axibound_V_1(p_channel_dout),
    .ap_return(Mat2Axi_Block_split24_proc_U0_ap_return)
);

median_blur_accel_Mat2AxiStream Mat2AxiStream_U0(
    .imgOutput_420_dout(imgOutput_420_dout),
    .imgOutput_420_empty_n(imgOutput_420_empty_n),
    .imgOutput_420_read(Mat2AxiStream_U0_imgOutput_420_read),
    .ldata1_din(Mat2AxiStream_U0_ldata1_din),
    .ldata1_full_n(ldata_full_n),
    .ldata1_write(Mat2AxiStream_U0_ldata1_write),
    .rows_dout(rows_c11_dout),
    .rows_empty_n(rows_c11_empty_n),
    .rows_read(Mat2AxiStream_U0_rows_read),
    .cols_dout(cols_c12_dout),
    .cols_empty_n(cols_c12_empty_n),
    .cols_read(Mat2AxiStream_U0_cols_read),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Mat2AxiStream_U0_ap_start),
    .ap_done(Mat2AxiStream_U0_ap_done),
    .ap_ready(Mat2AxiStream_U0_ap_ready),
    .ap_idle(Mat2AxiStream_U0_ap_idle),
    .ap_continue(Mat2AxiStream_U0_ap_continue)
);

median_blur_accel_AxiStream2Axi AxiStream2Axi_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(AxiStream2Axi_U0_ap_start),
    .ap_done(AxiStream2Axi_U0_ap_done),
    .ap_continue(AxiStream2Axi_U0_ap_continue),
    .ap_idle(AxiStream2Axi_U0_ap_idle),
    .ap_ready(AxiStream2Axi_U0_ap_ready),
    .ldata1_dout(ldata_dout),
    .ldata1_empty_n(ldata_empty_n),
    .ldata1_read(AxiStream2Axi_U0_ldata1_read),
    .m_axi_gmem1_AWVALID(AxiStream2Axi_U0_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(m_axi_gmem1_AWREADY),
    .m_axi_gmem1_AWADDR(AxiStream2Axi_U0_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(AxiStream2Axi_U0_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(AxiStream2Axi_U0_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(AxiStream2Axi_U0_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(AxiStream2Axi_U0_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(AxiStream2Axi_U0_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(AxiStream2Axi_U0_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(AxiStream2Axi_U0_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(AxiStream2Axi_U0_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(AxiStream2Axi_U0_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(AxiStream2Axi_U0_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(AxiStream2Axi_U0_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(m_axi_gmem1_WREADY),
    .m_axi_gmem1_WDATA(AxiStream2Axi_U0_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(AxiStream2Axi_U0_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(AxiStream2Axi_U0_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(AxiStream2Axi_U0_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(AxiStream2Axi_U0_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(AxiStream2Axi_U0_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(1'b0),
    .m_axi_gmem1_ARADDR(AxiStream2Axi_U0_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(AxiStream2Axi_U0_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(AxiStream2Axi_U0_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(AxiStream2Axi_U0_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(AxiStream2Axi_U0_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(AxiStream2Axi_U0_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(AxiStream2Axi_U0_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(AxiStream2Axi_U0_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(AxiStream2Axi_U0_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(AxiStream2Axi_U0_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(AxiStream2Axi_U0_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(1'b0),
    .m_axi_gmem1_RREADY(AxiStream2Axi_U0_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(32'd0),
    .m_axi_gmem1_RLAST(1'b0),
    .m_axi_gmem1_RID(1'd0),
    .m_axi_gmem1_RUSER(1'd0),
    .m_axi_gmem1_RRESP(2'd0),
    .m_axi_gmem1_BVALID(m_axi_gmem1_BVALID),
    .m_axi_gmem1_BREADY(AxiStream2Axi_U0_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(m_axi_gmem1_BRESP),
    .m_axi_gmem1_BID(m_axi_gmem1_BID),
    .m_axi_gmem1_BUSER(m_axi_gmem1_BUSER),
    .dout_dout(dout_c_dout),
    .dout_empty_n(dout_c_empty_n),
    .dout_read(AxiStream2Axi_U0_dout_read),
    .addrbound_V_read(axibound_V_dout)
);

median_blur_accel_fifo_w64_d4_S_x dout_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Mat2Axi_entry28_U0_dout_out_din),
    .if_full_n(dout_c_full_n),
    .if_write(Mat2Axi_entry28_U0_dout_out_write),
    .if_dout(dout_c_dout),
    .if_empty_n(dout_c_empty_n),
    .if_read(AxiStream2Axi_U0_dout_read)
);

median_blur_accel_fifo_w13_d2_S rows_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Mat2Axi_entry28_U0_rows_out_din),
    .if_full_n(rows_c_full_n),
    .if_write(Mat2Axi_entry28_U0_rows_out_write),
    .if_dout(rows_c_dout),
    .if_empty_n(rows_c_empty_n),
    .if_read(addrbound_U0_rows_read)
);

median_blur_accel_fifo_w32_d2_S_x0 rows_c11_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Mat2Axi_entry28_U0_rows_out1_din),
    .if_full_n(rows_c11_full_n),
    .if_write(Mat2Axi_entry28_U0_rows_out1_write),
    .if_dout(rows_c11_dout),
    .if_empty_n(rows_c11_empty_n),
    .if_read(Mat2AxiStream_U0_rows_read)
);

median_blur_accel_fifo_w16_d2_S cols_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Mat2Axi_entry28_U0_cols_out_din),
    .if_full_n(cols_c_full_n),
    .if_write(Mat2Axi_entry28_U0_cols_out_write),
    .if_dout(cols_c_dout),
    .if_empty_n(cols_c_empty_n),
    .if_read(addrbound_U0_cols_read)
);

median_blur_accel_fifo_w32_d2_S_x0 cols_c12_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Mat2Axi_entry28_U0_cols_out2_din),
    .if_full_n(cols_c12_full_n),
    .if_write(Mat2Axi_entry28_U0_cols_out2_write),
    .if_dout(cols_c12_dout),
    .if_empty_n(cols_c12_empty_n),
    .if_read(Mat2AxiStream_U0_cols_read)
);

median_blur_accel_fifo_w11_d2_S_x p_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(addrbound_U0_return_r),
    .if_full_n(p_channel_full_n),
    .if_write(addrbound_U0_ap_done),
    .if_dout(p_channel_dout),
    .if_empty_n(p_channel_empty_n),
    .if_read(Mat2Axi_Block_split24_proc_U0_ap_ready)
);

median_blur_accel_fifo_w11_d2_S_x axibound_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Mat2Axi_Block_split24_proc_U0_ap_return),
    .if_full_n(axibound_V_full_n),
    .if_write(Mat2Axi_Block_split24_proc_U0_ap_done),
    .if_dout(axibound_V_dout),
    .if_empty_n(axibound_V_empty_n),
    .if_read(AxiStream2Axi_U0_ap_ready)
);

median_blur_accel_fifo_w32_d2_S_x0 ldata_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Mat2AxiStream_U0_ldata1_din),
    .if_full_n(ldata_full_n),
    .if_write(Mat2AxiStream_U0_ldata1_write),
    .if_dout(ldata_dout),
    .if_empty_n(ldata_empty_n),
    .if_read(AxiStream2Axi_U0_ldata1_read)
);

median_blur_accel_start_for_addrbound_U0 start_for_addrbound_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_addrbound_U0_din),
    .if_full_n(start_for_addrbound_U0_full_n),
    .if_write(Mat2Axi_entry28_U0_start_write),
    .if_dout(start_for_addrbound_U0_dout),
    .if_empty_n(start_for_addrbound_U0_empty_n),
    .if_read(addrbound_U0_ap_ready)
);

median_blur_accel_start_for_Mat2AxiStream_U0 start_for_Mat2AxiStream_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Mat2AxiStream_U0_din),
    .if_full_n(start_for_Mat2AxiStream_U0_full_n),
    .if_write(Mat2Axi_entry28_U0_start_write),
    .if_dout(start_for_Mat2AxiStream_U0_dout),
    .if_empty_n(start_for_Mat2AxiStream_U0_empty_n),
    .if_read(Mat2AxiStream_U0_ap_ready)
);

assign AxiStream2Axi_U0_ap_continue = ap_continue;

assign AxiStream2Axi_U0_ap_start = axibound_V_empty_n;

assign AxiStream2Axi_U0_start_full_n = 1'b1;

assign AxiStream2Axi_U0_start_write = 1'b0;

assign Mat2AxiStream_U0_ap_continue = 1'b1;

assign Mat2AxiStream_U0_ap_start = start_for_Mat2AxiStream_U0_empty_n;

assign Mat2AxiStream_U0_start_full_n = 1'b1;

assign Mat2AxiStream_U0_start_write = 1'b0;

assign Mat2Axi_Block_split24_proc_U0_ap_continue = axibound_V_full_n;

assign Mat2Axi_Block_split24_proc_U0_ap_start = p_channel_empty_n;

assign Mat2Axi_Block_split24_proc_U0_start_full_n = 1'b1;

assign Mat2Axi_Block_split24_proc_U0_start_write = 1'b0;

assign Mat2Axi_entry28_U0_ap_continue = 1'b1;

assign Mat2Axi_entry28_U0_ap_start = ap_start;

assign Mat2Axi_entry28_U0_start_full_n = (start_for_addrbound_U0_full_n & start_for_Mat2AxiStream_U0_full_n);

assign addrbound_U0_ap_continue = p_channel_full_n;

assign addrbound_U0_ap_start = start_for_addrbound_U0_empty_n;

assign addrbound_U0_start_full_n = 1'b1;

assign addrbound_U0_start_write = 1'b0;

assign ap_channel_done_axibound_V = Mat2Axi_Block_split24_proc_U0_ap_done;

assign ap_channel_done_p_channel = addrbound_U0_ap_done;

assign ap_done = AxiStream2Axi_U0_ap_done;

assign ap_idle = ((axibound_V_empty_n ^ 1'b1) & (p_channel_empty_n ^ 1'b1) & addrbound_U0_ap_idle & Mat2Axi_entry28_U0_ap_idle & Mat2Axi_Block_split24_proc_U0_ap_idle & Mat2AxiStream_U0_ap_idle & AxiStream2Axi_U0_ap_idle);

assign ap_ready = Mat2Axi_entry28_U0_ap_ready;

assign ap_sync_continue = ap_continue;

assign ap_sync_done = AxiStream2Axi_U0_ap_done;

assign ap_sync_ready = Mat2Axi_entry28_U0_ap_ready;

assign imgOutput_420_read = Mat2AxiStream_U0_imgOutput_420_read;

assign m_axi_gmem1_ARADDR = 64'd0;

assign m_axi_gmem1_ARBURST = 2'd0;

assign m_axi_gmem1_ARCACHE = 4'd0;

assign m_axi_gmem1_ARID = 1'd0;

assign m_axi_gmem1_ARLEN = 32'd0;

assign m_axi_gmem1_ARLOCK = 2'd0;

assign m_axi_gmem1_ARPROT = 3'd0;

assign m_axi_gmem1_ARQOS = 4'd0;

assign m_axi_gmem1_ARREGION = 4'd0;

assign m_axi_gmem1_ARSIZE = 3'd0;

assign m_axi_gmem1_ARUSER = 1'd0;

assign m_axi_gmem1_ARVALID = 1'b0;

assign m_axi_gmem1_AWADDR = AxiStream2Axi_U0_m_axi_gmem1_AWADDR;

assign m_axi_gmem1_AWBURST = AxiStream2Axi_U0_m_axi_gmem1_AWBURST;

assign m_axi_gmem1_AWCACHE = AxiStream2Axi_U0_m_axi_gmem1_AWCACHE;

assign m_axi_gmem1_AWID = AxiStream2Axi_U0_m_axi_gmem1_AWID;

assign m_axi_gmem1_AWLEN = AxiStream2Axi_U0_m_axi_gmem1_AWLEN;

assign m_axi_gmem1_AWLOCK = AxiStream2Axi_U0_m_axi_gmem1_AWLOCK;

assign m_axi_gmem1_AWPROT = AxiStream2Axi_U0_m_axi_gmem1_AWPROT;

assign m_axi_gmem1_AWQOS = AxiStream2Axi_U0_m_axi_gmem1_AWQOS;

assign m_axi_gmem1_AWREGION = AxiStream2Axi_U0_m_axi_gmem1_AWREGION;

assign m_axi_gmem1_AWSIZE = AxiStream2Axi_U0_m_axi_gmem1_AWSIZE;

assign m_axi_gmem1_AWUSER = AxiStream2Axi_U0_m_axi_gmem1_AWUSER;

assign m_axi_gmem1_AWVALID = AxiStream2Axi_U0_m_axi_gmem1_AWVALID;

assign m_axi_gmem1_BREADY = AxiStream2Axi_U0_m_axi_gmem1_BREADY;

assign m_axi_gmem1_RREADY = 1'b0;

assign m_axi_gmem1_WDATA = AxiStream2Axi_U0_m_axi_gmem1_WDATA;

assign m_axi_gmem1_WID = AxiStream2Axi_U0_m_axi_gmem1_WID;

assign m_axi_gmem1_WLAST = AxiStream2Axi_U0_m_axi_gmem1_WLAST;

assign m_axi_gmem1_WSTRB = AxiStream2Axi_U0_m_axi_gmem1_WSTRB;

assign m_axi_gmem1_WUSER = AxiStream2Axi_U0_m_axi_gmem1_WUSER;

assign m_axi_gmem1_WVALID = AxiStream2Axi_U0_m_axi_gmem1_WVALID;

assign start_for_Mat2AxiStream_U0_din = 1'b1;

assign start_for_addrbound_U0_din = 1'b1;

endmodule //median_blur_accel_Mat2Axi
