// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="arithm_accel_arithm_accel,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=1165,HLS_SYN_TPT=1154,HLS_SYN_MEM=6,HLS_SYN_DSP=0,HLS_SYN_FF=9747,HLS_SYN_LUT=11204,HLS_VERSION=2020_2}" *)

module arithm_accel (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        s_axi_control_r_AWVALID,
        s_axi_control_r_AWREADY,
        s_axi_control_r_AWADDR,
        s_axi_control_r_WVALID,
        s_axi_control_r_WREADY,
        s_axi_control_r_WDATA,
        s_axi_control_r_WSTRB,
        s_axi_control_r_ARVALID,
        s_axi_control_r_ARREADY,
        s_axi_control_r_ARADDR,
        s_axi_control_r_RVALID,
        s_axi_control_r_RREADY,
        s_axi_control_r_RDATA,
        s_axi_control_r_RRESP,
        s_axi_control_r_BVALID,
        s_axi_control_r_BREADY,
        s_axi_control_r_BRESP,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        m_axi_gmem2_AWVALID,
        m_axi_gmem2_AWREADY,
        m_axi_gmem2_AWADDR,
        m_axi_gmem2_AWID,
        m_axi_gmem2_AWLEN,
        m_axi_gmem2_AWSIZE,
        m_axi_gmem2_AWBURST,
        m_axi_gmem2_AWLOCK,
        m_axi_gmem2_AWCACHE,
        m_axi_gmem2_AWPROT,
        m_axi_gmem2_AWQOS,
        m_axi_gmem2_AWREGION,
        m_axi_gmem2_AWUSER,
        m_axi_gmem2_WVALID,
        m_axi_gmem2_WREADY,
        m_axi_gmem2_WDATA,
        m_axi_gmem2_WSTRB,
        m_axi_gmem2_WLAST,
        m_axi_gmem2_WID,
        m_axi_gmem2_WUSER,
        m_axi_gmem2_ARVALID,
        m_axi_gmem2_ARREADY,
        m_axi_gmem2_ARADDR,
        m_axi_gmem2_ARID,
        m_axi_gmem2_ARLEN,
        m_axi_gmem2_ARSIZE,
        m_axi_gmem2_ARBURST,
        m_axi_gmem2_ARLOCK,
        m_axi_gmem2_ARCACHE,
        m_axi_gmem2_ARPROT,
        m_axi_gmem2_ARQOS,
        m_axi_gmem2_ARREGION,
        m_axi_gmem2_ARUSER,
        m_axi_gmem2_RVALID,
        m_axi_gmem2_RREADY,
        m_axi_gmem2_RDATA,
        m_axi_gmem2_RLAST,
        m_axi_gmem2_RID,
        m_axi_gmem2_RUSER,
        m_axi_gmem2_RRESP,
        m_axi_gmem2_BVALID,
        m_axi_gmem2_BREADY,
        m_axi_gmem2_BRESP,
        m_axi_gmem2_BID,
        m_axi_gmem2_BUSER,
        height,
        width
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_ADDR_WIDTH = 32;
parameter    C_S_AXI_CONTROL_R_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_R_ADDR_WIDTH = 6;
parameter    C_M_AXI_GMEM0_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM0_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_USER_VALUE = 0;
parameter    C_M_AXI_GMEM0_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM0_CACHE_VALUE = 3;
parameter    C_M_AXI_ID_WIDTH = 1;
parameter    C_M_AXI_ADDR_WIDTH = 64;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_AWUSER_WIDTH = 1;
parameter    C_M_AXI_ARUSER_WIDTH = 1;
parameter    C_M_AXI_WUSER_WIDTH = 1;
parameter    C_M_AXI_RUSER_WIDTH = 1;
parameter    C_M_AXI_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;
parameter    C_M_AXI_GMEM2_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM2_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM2_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_USER_VALUE = 0;
parameter    C_M_AXI_GMEM2_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM2_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_CONTROL_R_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM0_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM2_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
input   s_axi_control_r_AWVALID;
output   s_axi_control_r_AWREADY;
input  [C_S_AXI_CONTROL_R_ADDR_WIDTH - 1:0] s_axi_control_r_AWADDR;
input   s_axi_control_r_WVALID;
output   s_axi_control_r_WREADY;
input  [C_S_AXI_CONTROL_R_DATA_WIDTH - 1:0] s_axi_control_r_WDATA;
input  [C_S_AXI_CONTROL_R_WSTRB_WIDTH - 1:0] s_axi_control_r_WSTRB;
input   s_axi_control_r_ARVALID;
output   s_axi_control_r_ARREADY;
input  [C_S_AXI_CONTROL_R_ADDR_WIDTH - 1:0] s_axi_control_r_ARADDR;
output   s_axi_control_r_RVALID;
input   s_axi_control_r_RREADY;
output  [C_S_AXI_CONTROL_R_DATA_WIDTH - 1:0] s_axi_control_r_RDATA;
output  [1:0] s_axi_control_r_RRESP;
output   s_axi_control_r_BVALID;
input   s_axi_control_r_BREADY;
output  [1:0] s_axi_control_r_BRESP;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_AWADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_AWID;
output  [7:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [C_M_AXI_GMEM0_AWUSER_WIDTH - 1:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_WDATA;
output  [C_M_AXI_GMEM0_WSTRB_WIDTH - 1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_WID;
output  [C_M_AXI_GMEM0_WUSER_WIDTH - 1:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_ARADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_ARID;
output  [7:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [C_M_AXI_GMEM0_ARUSER_WIDTH - 1:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_RID;
input  [C_M_AXI_GMEM0_RUSER_WIDTH - 1:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_BID;
input  [C_M_AXI_GMEM0_BUSER_WIDTH - 1:0] m_axi_gmem0_BUSER;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;
output   m_axi_gmem2_AWVALID;
input   m_axi_gmem2_AWREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_AWADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_AWID;
output  [7:0] m_axi_gmem2_AWLEN;
output  [2:0] m_axi_gmem2_AWSIZE;
output  [1:0] m_axi_gmem2_AWBURST;
output  [1:0] m_axi_gmem2_AWLOCK;
output  [3:0] m_axi_gmem2_AWCACHE;
output  [2:0] m_axi_gmem2_AWPROT;
output  [3:0] m_axi_gmem2_AWQOS;
output  [3:0] m_axi_gmem2_AWREGION;
output  [C_M_AXI_GMEM2_AWUSER_WIDTH - 1:0] m_axi_gmem2_AWUSER;
output   m_axi_gmem2_WVALID;
input   m_axi_gmem2_WREADY;
output  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_WDATA;
output  [C_M_AXI_GMEM2_WSTRB_WIDTH - 1:0] m_axi_gmem2_WSTRB;
output   m_axi_gmem2_WLAST;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_WID;
output  [C_M_AXI_GMEM2_WUSER_WIDTH - 1:0] m_axi_gmem2_WUSER;
output   m_axi_gmem2_ARVALID;
input   m_axi_gmem2_ARREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_ARADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_ARID;
output  [7:0] m_axi_gmem2_ARLEN;
output  [2:0] m_axi_gmem2_ARSIZE;
output  [1:0] m_axi_gmem2_ARBURST;
output  [1:0] m_axi_gmem2_ARLOCK;
output  [3:0] m_axi_gmem2_ARCACHE;
output  [2:0] m_axi_gmem2_ARPROT;
output  [3:0] m_axi_gmem2_ARQOS;
output  [3:0] m_axi_gmem2_ARREGION;
output  [C_M_AXI_GMEM2_ARUSER_WIDTH - 1:0] m_axi_gmem2_ARUSER;
input   m_axi_gmem2_RVALID;
output   m_axi_gmem2_RREADY;
input  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_RDATA;
input   m_axi_gmem2_RLAST;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_RID;
input  [C_M_AXI_GMEM2_RUSER_WIDTH - 1:0] m_axi_gmem2_RUSER;
input  [1:0] m_axi_gmem2_RRESP;
input   m_axi_gmem2_BVALID;
output   m_axi_gmem2_BREADY;
input  [1:0] m_axi_gmem2_BRESP;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_BID;
input  [C_M_AXI_GMEM2_BUSER_WIDTH - 1:0] m_axi_gmem2_BUSER;
input  [31:0] height;
input  [31:0] width;

 reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire   [63:0] img_in1;
wire   [63:0] img_in2;
wire   [63:0] img_out;
wire    gmem0_AWREADY;
wire    gmem0_WREADY;
wire    gmem0_ARREADY;
wire    gmem0_RVALID;
wire   [7:0] gmem0_RDATA;
wire    gmem0_RLAST;
wire   [0:0] gmem0_RID;
wire   [0:0] gmem0_RUSER;
wire   [1:0] gmem0_RRESP;
wire    gmem0_BVALID;
wire   [1:0] gmem0_BRESP;
wire   [0:0] gmem0_BID;
wire   [0:0] gmem0_BUSER;
wire    gmem1_AWREADY;
wire    gmem1_WREADY;
wire    gmem1_ARREADY;
wire    gmem1_RVALID;
wire   [7:0] gmem1_RDATA;
wire    gmem1_RLAST;
wire   [0:0] gmem1_RID;
wire   [0:0] gmem1_RUSER;
wire   [1:0] gmem1_RRESP;
wire    gmem1_BVALID;
wire   [1:0] gmem1_BRESP;
wire   [0:0] gmem1_BID;
wire   [0:0] gmem1_BUSER;
wire    gmem2_AWREADY;
wire    gmem2_WREADY;
wire    gmem2_ARREADY;
wire    gmem2_RVALID;
wire   [7:0] gmem2_RDATA;
wire    gmem2_RLAST;
wire   [0:0] gmem2_RID;
wire   [0:0] gmem2_RUSER;
wire   [1:0] gmem2_RRESP;
wire    gmem2_BVALID;
wire   [1:0] gmem2_BRESP;
wire   [0:0] gmem2_BID;
wire   [0:0] gmem2_BUSER;
wire    Block_split1_proc22_U0_ap_start;
wire    Block_split1_proc22_U0_ap_done;
wire    Block_split1_proc22_U0_ap_continue;
wire    Block_split1_proc22_U0_ap_idle;
wire    Block_split1_proc22_U0_ap_ready;
wire    Block_split1_proc22_U0_start_out;
wire    Block_split1_proc22_U0_start_write;
wire   [31:0] Block_split1_proc22_U0_imgInput1_rows_out_din;
wire    Block_split1_proc22_U0_imgInput1_rows_out_write;
wire   [31:0] Block_split1_proc22_U0_imgInput1_cols_out_din;
wire    Block_split1_proc22_U0_imgInput1_cols_out_write;
wire   [31:0] Block_split1_proc22_U0_imgOutput_rows_out_din;
wire    Block_split1_proc22_U0_imgOutput_rows_out_write;
wire   [31:0] Block_split1_proc22_U0_imgOutput_cols_out_din;
wire    Block_split1_proc22_U0_imgOutput_cols_out_write;
wire   [63:0] Block_split1_proc22_U0_img_in1_out_din;
wire    Block_split1_proc22_U0_img_in1_out_write;
wire   [63:0] Block_split1_proc22_U0_img_in2_out_din;
wire    Block_split1_proc22_U0_img_in2_out_write;
wire   [63:0] Block_split1_proc22_U0_img_out_out_din;
wire    Block_split1_proc22_U0_img_out_out_write;
wire   [31:0] Block_split1_proc22_U0_ap_return_0;
wire   [31:0] Block_split1_proc22_U0_ap_return_1;
wire    ap_channel_done_imgInput2_cols_channel;
wire    imgInput2_cols_channel_full_n;
reg    ap_sync_reg_channel_write_imgInput2_cols_channel;
wire    ap_sync_channel_write_imgInput2_cols_channel;
wire    ap_channel_done_imgInput2_rows_channel;
wire    imgInput2_rows_channel_full_n;
reg    ap_sync_reg_channel_write_imgInput2_rows_channel;
wire    ap_sync_channel_write_imgInput2_rows_channel;
wire    Array2xfMat_8_0_32_32_1_5_U0_ap_start;
wire    Array2xfMat_8_0_32_32_1_5_U0_ap_done;
wire    Array2xfMat_8_0_32_32_1_5_U0_ap_continue;
wire    Array2xfMat_8_0_32_32_1_5_U0_ap_idle;
wire    Array2xfMat_8_0_32_32_1_5_U0_ap_ready;
wire    Array2xfMat_8_0_32_32_1_5_U0_start_out;
wire    Array2xfMat_8_0_32_32_1_5_U0_start_write;
wire    Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_AWVALID;
wire   [63:0] Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_AWADDR;
wire   [0:0] Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_AWID;
wire   [31:0] Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_AWLEN;
wire   [2:0] Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_AWSIZE;
wire   [1:0] Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_AWBURST;
wire   [1:0] Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_AWLOCK;
wire   [3:0] Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_AWCACHE;
wire   [2:0] Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_AWPROT;
wire   [3:0] Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_AWQOS;
wire   [3:0] Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_AWREGION;
wire   [0:0] Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_AWUSER;
wire    Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_WVALID;
wire   [7:0] Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_WDATA;
wire   [0:0] Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_WSTRB;
wire    Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_WLAST;
wire   [0:0] Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_WID;
wire   [0:0] Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_WUSER;
wire    Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARVALID;
wire   [63:0] Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARADDR;
wire   [0:0] Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARID;
wire   [31:0] Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARLEN;
wire   [2:0] Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARSIZE;
wire   [1:0] Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARBURST;
wire   [1:0] Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARLOCK;
wire   [3:0] Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARCACHE;
wire   [2:0] Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARPROT;
wire   [3:0] Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARQOS;
wire   [3:0] Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARREGION;
wire   [0:0] Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARUSER;
wire    Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_RREADY;
wire    Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_BREADY;
wire   [7:0] Array2xfMat_8_0_32_32_1_5_U0_imgInput1_434_din;
wire    Array2xfMat_8_0_32_32_1_5_U0_imgInput1_434_write;
wire    Array2xfMat_8_0_32_32_1_5_U0_srcPtr_read;
wire    Array2xfMat_8_0_32_32_1_5_U0_dstMat_rows_read;
wire    Array2xfMat_8_0_32_32_1_5_U0_dstMat_cols_read;
wire   [31:0] Array2xfMat_8_0_32_32_1_5_U0_dstMat_rows_out_din;
wire    Array2xfMat_8_0_32_32_1_5_U0_dstMat_rows_out_write;
wire   [31:0] Array2xfMat_8_0_32_32_1_5_U0_dstMat_cols_out_din;
wire    Array2xfMat_8_0_32_32_1_5_U0_dstMat_cols_out_write;
wire    Array2xfMat_8_0_32_32_1_U0_ap_start;
wire    Array2xfMat_8_0_32_32_1_U0_ap_done;
wire    Array2xfMat_8_0_32_32_1_U0_ap_continue;
wire    Array2xfMat_8_0_32_32_1_U0_ap_idle;
wire    Array2xfMat_8_0_32_32_1_U0_ap_ready;
wire    Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_AWVALID;
wire   [63:0] Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_AWADDR;
wire   [0:0] Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_AWID;
wire   [31:0] Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_AWLEN;
wire   [2:0] Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_AWSIZE;
wire   [1:0] Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_AWBURST;
wire   [1:0] Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_AWLOCK;
wire   [3:0] Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_AWCACHE;
wire   [2:0] Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_AWPROT;
wire   [3:0] Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_AWQOS;
wire   [3:0] Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_AWREGION;
wire   [0:0] Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_AWUSER;
wire    Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_WVALID;
wire   [7:0] Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_WDATA;
wire   [0:0] Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_WSTRB;
wire    Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_WLAST;
wire   [0:0] Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_WID;
wire   [0:0] Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_WUSER;
wire    Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARVALID;
wire   [63:0] Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARADDR;
wire   [0:0] Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARID;
wire   [31:0] Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARLEN;
wire   [2:0] Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARSIZE;
wire   [1:0] Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARBURST;
wire   [1:0] Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARLOCK;
wire   [3:0] Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARCACHE;
wire   [2:0] Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARPROT;
wire   [3:0] Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARQOS;
wire   [3:0] Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARREGION;
wire   [0:0] Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARUSER;
wire    Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_RREADY;
wire    Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_BREADY;
wire   [7:0] Array2xfMat_8_0_32_32_1_U0_imgInput1_434_din;
wire    Array2xfMat_8_0_32_32_1_U0_imgInput1_434_write;
wire    Array2xfMat_8_0_32_32_1_U0_srcPtr_read;
wire    absdiff_0_32_32_1_U0_ap_start;
wire    absdiff_0_32_32_1_U0_ap_done;
wire    absdiff_0_32_32_1_U0_ap_continue;
wire    absdiff_0_32_32_1_U0_ap_idle;
wire    absdiff_0_32_32_1_U0_ap_ready;
wire    absdiff_0_32_32_1_U0_imgInput1_434_read;
wire    absdiff_0_32_32_1_U0_imgInput2_435_read;
wire   [7:0] absdiff_0_32_32_1_U0_imgOutput_436_din;
wire    absdiff_0_32_32_1_U0_imgOutput_436_write;
wire    absdiff_0_32_32_1_U0_p_src1_rows_read;
wire    absdiff_0_32_32_1_U0_p_src1_cols_read;
wire    xfMat2Array_8_0_32_32_1_1_U0_ap_start;
wire    xfMat2Array_8_0_32_32_1_1_U0_ap_done;
wire    xfMat2Array_8_0_32_32_1_1_U0_ap_continue;
wire    xfMat2Array_8_0_32_32_1_1_U0_ap_idle;
wire    xfMat2Array_8_0_32_32_1_1_U0_ap_ready;
wire    xfMat2Array_8_0_32_32_1_1_U0_imgOutput_436_read;
wire    xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWVALID;
wire   [63:0] xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWADDR;
wire   [0:0] xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWID;
wire   [31:0] xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWLEN;
wire   [2:0] xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWSIZE;
wire   [1:0] xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWBURST;
wire   [1:0] xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWLOCK;
wire   [3:0] xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWCACHE;
wire   [2:0] xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWPROT;
wire   [3:0] xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWQOS;
wire   [3:0] xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWREGION;
wire   [0:0] xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWUSER;
wire    xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_WVALID;
wire   [7:0] xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_WDATA;
wire   [0:0] xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_WSTRB;
wire    xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_WLAST;
wire   [0:0] xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_WID;
wire   [0:0] xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_WUSER;
wire    xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_ARVALID;
wire   [63:0] xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_ARADDR;
wire   [0:0] xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_ARID;
wire   [31:0] xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_ARLEN;
wire   [2:0] xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_ARSIZE;
wire   [1:0] xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_ARBURST;
wire   [1:0] xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_ARLOCK;
wire   [3:0] xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_ARCACHE;
wire   [2:0] xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_ARPROT;
wire   [3:0] xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_ARQOS;
wire   [3:0] xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_ARREGION;
wire   [0:0] xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_ARUSER;
wire    xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_RREADY;
wire    xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_BREADY;
wire    xfMat2Array_8_0_32_32_1_1_U0_srcMat_rows_read;
wire    xfMat2Array_8_0_32_32_1_1_U0_srcMat_cols_read;
wire    xfMat2Array_8_0_32_32_1_1_U0_dstPtr_read;
wire    ap_sync_continue;
wire    imgInput1_rows_c_full_n;
wire   [31:0] imgInput1_rows_c_dout;
wire    imgInput1_rows_c_empty_n;
wire    imgInput1_cols_c_full_n;
wire   [31:0] imgInput1_cols_c_dout;
wire    imgInput1_cols_c_empty_n;
wire    imgOutput_rows_c_full_n;
wire   [31:0] imgOutput_rows_c_dout;
wire    imgOutput_rows_c_empty_n;
wire    imgOutput_cols_c_full_n;
wire   [31:0] imgOutput_cols_c_dout;
wire    imgOutput_cols_c_empty_n;
wire    img_in1_c_full_n;
wire   [63:0] img_in1_c_dout;
wire    img_in1_c_empty_n;
wire    img_in2_c_full_n;
wire   [63:0] img_in2_c_dout;
wire    img_in2_c_empty_n;
wire    img_out_c_full_n;
wire   [63:0] img_out_c_dout;
wire    img_out_c_empty_n;
wire   [31:0] imgInput2_rows_channel_dout;
wire    imgInput2_rows_channel_empty_n;
wire   [31:0] imgInput2_cols_channel_dout;
wire    imgInput2_cols_channel_empty_n;
wire    imgInput1_data_full_n;
wire   [7:0] imgInput1_data_dout;
wire    imgInput1_data_empty_n;
wire    imgInput1_rows_c11_full_n;
wire   [31:0] imgInput1_rows_c11_dout;
wire    imgInput1_rows_c11_empty_n;
wire    imgInput1_cols_c12_full_n;
wire   [31:0] imgInput1_cols_c12_dout;
wire    imgInput1_cols_c12_empty_n;
wire    imgInput2_data_full_n;
wire   [7:0] imgInput2_data_dout;
wire    imgInput2_data_empty_n;
wire    imgOutput_data_full_n;
wire   [7:0] imgOutput_data_dout;
wire    imgOutput_data_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_Block_split1_proc22_U0_ap_ready;
wire    ap_sync_Block_split1_proc22_U0_ap_ready;
reg    ap_sync_reg_Array2xfMat_8_0_32_32_1_5_U0_ap_ready;
wire    ap_sync_Array2xfMat_8_0_32_32_1_5_U0_ap_ready;
reg    ap_sync_reg_Array2xfMat_8_0_32_32_1_U0_ap_ready;
wire    ap_sync_Array2xfMat_8_0_32_32_1_U0_ap_ready;
wire   [0:0] start_for_xfMat2Array_8_0_32_32_1_1_U0_din;
wire    start_for_xfMat2Array_8_0_32_32_1_1_U0_full_n;
wire   [0:0] start_for_xfMat2Array_8_0_32_32_1_1_U0_dout;
wire    start_for_xfMat2Array_8_0_32_32_1_1_U0_empty_n;
wire   [0:0] start_for_absdiff_0_32_32_1_U0_din;
wire    start_for_absdiff_0_32_32_1_U0_full_n;
wire   [0:0] start_for_absdiff_0_32_32_1_U0_dout;
wire    start_for_absdiff_0_32_32_1_U0_empty_n;
wire    Array2xfMat_8_0_32_32_1_U0_start_full_n;
wire    Array2xfMat_8_0_32_32_1_U0_start_write;
wire    absdiff_0_32_32_1_U0_start_full_n;
wire    absdiff_0_32_32_1_U0_start_write;
wire    xfMat2Array_8_0_32_32_1_1_U0_start_full_n;
wire    xfMat2Array_8_0_32_32_1_1_U0_start_write;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_imgInput2_cols_channel = 1'b0;
#0 ap_sync_reg_channel_write_imgInput2_rows_channel = 1'b0;
#0 ap_sync_reg_Block_split1_proc22_U0_ap_ready = 1'b0;
#0 ap_sync_reg_Array2xfMat_8_0_32_32_1_5_U0_ap_ready = 1'b0;
#0 ap_sync_reg_Array2xfMat_8_0_32_32_1_U0_ap_ready = 1'b0;
end

arithm_accel_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

arithm_accel_control_r_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_R_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_R_DATA_WIDTH ))
control_r_s_axi_U(
    .AWVALID(s_axi_control_r_AWVALID),
    .AWREADY(s_axi_control_r_AWREADY),
    .AWADDR(s_axi_control_r_AWADDR),
    .WVALID(s_axi_control_r_WVALID),
    .WREADY(s_axi_control_r_WREADY),
    .WDATA(s_axi_control_r_WDATA),
    .WSTRB(s_axi_control_r_WSTRB),
    .ARVALID(s_axi_control_r_ARVALID),
    .ARREADY(s_axi_control_r_ARREADY),
    .ARADDR(s_axi_control_r_ARADDR),
    .RVALID(s_axi_control_r_RVALID),
    .RREADY(s_axi_control_r_RREADY),
    .RDATA(s_axi_control_r_RDATA),
    .RRESP(s_axi_control_r_RRESP),
    .BVALID(s_axi_control_r_BVALID),
    .BREADY(s_axi_control_r_BREADY),
    .BRESP(s_axi_control_r_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .img_in1(img_in1),
    .img_in2(img_in2),
    .img_out(img_out)
);

arithm_accel_gmem0_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 8 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM0_CACHE_VALUE ))
gmem0_m_axi_U(
    .AWVALID(m_axi_gmem0_AWVALID),
    .AWREADY(m_axi_gmem0_AWREADY),
    .AWADDR(m_axi_gmem0_AWADDR),
    .AWID(m_axi_gmem0_AWID),
    .AWLEN(m_axi_gmem0_AWLEN),
    .AWSIZE(m_axi_gmem0_AWSIZE),
    .AWBURST(m_axi_gmem0_AWBURST),
    .AWLOCK(m_axi_gmem0_AWLOCK),
    .AWCACHE(m_axi_gmem0_AWCACHE),
    .AWPROT(m_axi_gmem0_AWPROT),
    .AWQOS(m_axi_gmem0_AWQOS),
    .AWREGION(m_axi_gmem0_AWREGION),
    .AWUSER(m_axi_gmem0_AWUSER),
    .WVALID(m_axi_gmem0_WVALID),
    .WREADY(m_axi_gmem0_WREADY),
    .WDATA(m_axi_gmem0_WDATA),
    .WSTRB(m_axi_gmem0_WSTRB),
    .WLAST(m_axi_gmem0_WLAST),
    .WID(m_axi_gmem0_WID),
    .WUSER(m_axi_gmem0_WUSER),
    .ARVALID(m_axi_gmem0_ARVALID),
    .ARREADY(m_axi_gmem0_ARREADY),
    .ARADDR(m_axi_gmem0_ARADDR),
    .ARID(m_axi_gmem0_ARID),
    .ARLEN(m_axi_gmem0_ARLEN),
    .ARSIZE(m_axi_gmem0_ARSIZE),
    .ARBURST(m_axi_gmem0_ARBURST),
    .ARLOCK(m_axi_gmem0_ARLOCK),
    .ARCACHE(m_axi_gmem0_ARCACHE),
    .ARPROT(m_axi_gmem0_ARPROT),
    .ARQOS(m_axi_gmem0_ARQOS),
    .ARREGION(m_axi_gmem0_ARREGION),
    .ARUSER(m_axi_gmem0_ARUSER),
    .RVALID(m_axi_gmem0_RVALID),
    .RREADY(m_axi_gmem0_RREADY),
    .RDATA(m_axi_gmem0_RDATA),
    .RLAST(m_axi_gmem0_RLAST),
    .RID(m_axi_gmem0_RID),
    .RUSER(m_axi_gmem0_RUSER),
    .RRESP(m_axi_gmem0_RRESP),
    .BVALID(m_axi_gmem0_BVALID),
    .BREADY(m_axi_gmem0_BREADY),
    .BRESP(m_axi_gmem0_BRESP),
    .BID(m_axi_gmem0_BID),
    .BUSER(m_axi_gmem0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARVALID),
    .I_ARREADY(gmem0_ARREADY),
    .I_ARADDR(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARADDR),
    .I_ARID(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARID),
    .I_ARLEN(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARLEN),
    .I_ARSIZE(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARSIZE),
    .I_ARLOCK(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARLOCK),
    .I_ARCACHE(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARCACHE),
    .I_ARQOS(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARQOS),
    .I_ARPROT(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARPROT),
    .I_ARUSER(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARUSER),
    .I_ARBURST(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARBURST),
    .I_ARREGION(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARREGION),
    .I_RVALID(gmem0_RVALID),
    .I_RREADY(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_RREADY),
    .I_RDATA(gmem0_RDATA),
    .I_RID(gmem0_RID),
    .I_RUSER(gmem0_RUSER),
    .I_RRESP(gmem0_RRESP),
    .I_RLAST(gmem0_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem0_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem0_WREADY),
    .I_WDATA(8'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(1'd0),
    .I_BVALID(gmem0_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(gmem0_BRESP),
    .I_BID(gmem0_BID),
    .I_BUSER(gmem0_BUSER)
);

arithm_accel_gmem1_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 8 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ))
gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARVALID),
    .I_ARREADY(gmem1_ARREADY),
    .I_ARADDR(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARADDR),
    .I_ARID(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARID),
    .I_ARLEN(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARLEN),
    .I_ARSIZE(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARSIZE),
    .I_ARLOCK(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARLOCK),
    .I_ARCACHE(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARCACHE),
    .I_ARQOS(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARQOS),
    .I_ARPROT(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARPROT),
    .I_ARUSER(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARUSER),
    .I_ARBURST(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARBURST),
    .I_ARREGION(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARREGION),
    .I_RVALID(gmem1_RVALID),
    .I_RREADY(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_RREADY),
    .I_RDATA(gmem1_RDATA),
    .I_RID(gmem1_RID),
    .I_RUSER(gmem1_RUSER),
    .I_RRESP(gmem1_RRESP),
    .I_RLAST(gmem1_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem1_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem1_WREADY),
    .I_WDATA(8'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(1'd0),
    .I_BVALID(gmem1_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(gmem1_BRESP),
    .I_BID(gmem1_BID),
    .I_BUSER(gmem1_BUSER)
);

arithm_accel_gmem2_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 8 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM2_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM2_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM2_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM2_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM2_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM2_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM2_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM2_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM2_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM2_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM2_CACHE_VALUE ))
gmem2_m_axi_U(
    .AWVALID(m_axi_gmem2_AWVALID),
    .AWREADY(m_axi_gmem2_AWREADY),
    .AWADDR(m_axi_gmem2_AWADDR),
    .AWID(m_axi_gmem2_AWID),
    .AWLEN(m_axi_gmem2_AWLEN),
    .AWSIZE(m_axi_gmem2_AWSIZE),
    .AWBURST(m_axi_gmem2_AWBURST),
    .AWLOCK(m_axi_gmem2_AWLOCK),
    .AWCACHE(m_axi_gmem2_AWCACHE),
    .AWPROT(m_axi_gmem2_AWPROT),
    .AWQOS(m_axi_gmem2_AWQOS),
    .AWREGION(m_axi_gmem2_AWREGION),
    .AWUSER(m_axi_gmem2_AWUSER),
    .WVALID(m_axi_gmem2_WVALID),
    .WREADY(m_axi_gmem2_WREADY),
    .WDATA(m_axi_gmem2_WDATA),
    .WSTRB(m_axi_gmem2_WSTRB),
    .WLAST(m_axi_gmem2_WLAST),
    .WID(m_axi_gmem2_WID),
    .WUSER(m_axi_gmem2_WUSER),
    .ARVALID(m_axi_gmem2_ARVALID),
    .ARREADY(m_axi_gmem2_ARREADY),
    .ARADDR(m_axi_gmem2_ARADDR),
    .ARID(m_axi_gmem2_ARID),
    .ARLEN(m_axi_gmem2_ARLEN),
    .ARSIZE(m_axi_gmem2_ARSIZE),
    .ARBURST(m_axi_gmem2_ARBURST),
    .ARLOCK(m_axi_gmem2_ARLOCK),
    .ARCACHE(m_axi_gmem2_ARCACHE),
    .ARPROT(m_axi_gmem2_ARPROT),
    .ARQOS(m_axi_gmem2_ARQOS),
    .ARREGION(m_axi_gmem2_ARREGION),
    .ARUSER(m_axi_gmem2_ARUSER),
    .RVALID(m_axi_gmem2_RVALID),
    .RREADY(m_axi_gmem2_RREADY),
    .RDATA(m_axi_gmem2_RDATA),
    .RLAST(m_axi_gmem2_RLAST),
    .RID(m_axi_gmem2_RID),
    .RUSER(m_axi_gmem2_RUSER),
    .RRESP(m_axi_gmem2_RRESP),
    .BVALID(m_axi_gmem2_BVALID),
    .BREADY(m_axi_gmem2_BREADY),
    .BRESP(m_axi_gmem2_BRESP),
    .BID(m_axi_gmem2_BID),
    .BUSER(m_axi_gmem2_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(gmem2_ARREADY),
    .I_ARADDR(64'd0),
    .I_ARID(1'd0),
    .I_ARLEN(32'd0),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(gmem2_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(gmem2_RDATA),
    .I_RID(gmem2_RID),
    .I_RUSER(gmem2_RUSER),
    .I_RRESP(gmem2_RRESP),
    .I_RLAST(gmem2_RLAST),
    .I_AWVALID(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWVALID),
    .I_AWREADY(gmem2_AWREADY),
    .I_AWADDR(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWADDR),
    .I_AWID(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWID),
    .I_AWLEN(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWLEN),
    .I_AWSIZE(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWSIZE),
    .I_AWLOCK(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWLOCK),
    .I_AWCACHE(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWCACHE),
    .I_AWQOS(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWQOS),
    .I_AWPROT(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWPROT),
    .I_AWUSER(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWUSER),
    .I_AWBURST(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWBURST),
    .I_AWREGION(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWREGION),
    .I_WVALID(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_WVALID),
    .I_WREADY(gmem2_WREADY),
    .I_WDATA(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_WDATA),
    .I_WID(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_WID),
    .I_WUSER(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_WUSER),
    .I_WLAST(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_WLAST),
    .I_WSTRB(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_WSTRB),
    .I_BVALID(gmem2_BVALID),
    .I_BREADY(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_BREADY),
    .I_BRESP(gmem2_BRESP),
    .I_BID(gmem2_BID),
    .I_BUSER(gmem2_BUSER)
);

arithm_accel_Block_split1_proc22 Block_split1_proc22_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_split1_proc22_U0_ap_start),
    .start_full_n(start_for_xfMat2Array_8_0_32_32_1_1_U0_full_n),
    .ap_done(Block_split1_proc22_U0_ap_done),
    .ap_continue(Block_split1_proc22_U0_ap_continue),
    .ap_idle(Block_split1_proc22_U0_ap_idle),
    .ap_ready(Block_split1_proc22_U0_ap_ready),
    .start_out(Block_split1_proc22_U0_start_out),
    .start_write(Block_split1_proc22_U0_start_write),
    .height(height),
    .width(width),
    .img_in1(img_in1),
    .img_in2(img_in2),
    .img_out(img_out),
    .imgInput1_rows_out_din(Block_split1_proc22_U0_imgInput1_rows_out_din),
    .imgInput1_rows_out_full_n(imgInput1_rows_c_full_n),
    .imgInput1_rows_out_write(Block_split1_proc22_U0_imgInput1_rows_out_write),
    .imgInput1_cols_out_din(Block_split1_proc22_U0_imgInput1_cols_out_din),
    .imgInput1_cols_out_full_n(imgInput1_cols_c_full_n),
    .imgInput1_cols_out_write(Block_split1_proc22_U0_imgInput1_cols_out_write),
    .imgOutput_rows_out_din(Block_split1_proc22_U0_imgOutput_rows_out_din),
    .imgOutput_rows_out_full_n(imgOutput_rows_c_full_n),
    .imgOutput_rows_out_write(Block_split1_proc22_U0_imgOutput_rows_out_write),
    .imgOutput_cols_out_din(Block_split1_proc22_U0_imgOutput_cols_out_din),
    .imgOutput_cols_out_full_n(imgOutput_cols_c_full_n),
    .imgOutput_cols_out_write(Block_split1_proc22_U0_imgOutput_cols_out_write),
    .img_in1_out_din(Block_split1_proc22_U0_img_in1_out_din),
    .img_in1_out_full_n(img_in1_c_full_n),
    .img_in1_out_write(Block_split1_proc22_U0_img_in1_out_write),
    .img_in2_out_din(Block_split1_proc22_U0_img_in2_out_din),
    .img_in2_out_full_n(img_in2_c_full_n),
    .img_in2_out_write(Block_split1_proc22_U0_img_in2_out_write),
    .img_out_out_din(Block_split1_proc22_U0_img_out_out_din),
    .img_out_out_full_n(img_out_c_full_n),
    .img_out_out_write(Block_split1_proc22_U0_img_out_out_write),
    .ap_return_0(Block_split1_proc22_U0_ap_return_0),
    .ap_return_1(Block_split1_proc22_U0_ap_return_1)
);

arithm_accel_Array2xfMat_8_0_32_32_1_5 Array2xfMat_8_0_32_32_1_5_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Array2xfMat_8_0_32_32_1_5_U0_ap_start),
    .start_full_n(start_for_absdiff_0_32_32_1_U0_full_n),
    .ap_done(Array2xfMat_8_0_32_32_1_5_U0_ap_done),
    .ap_continue(Array2xfMat_8_0_32_32_1_5_U0_ap_continue),
    .ap_idle(Array2xfMat_8_0_32_32_1_5_U0_ap_idle),
    .ap_ready(Array2xfMat_8_0_32_32_1_5_U0_ap_ready),
    .start_out(Array2xfMat_8_0_32_32_1_5_U0_start_out),
    .start_write(Array2xfMat_8_0_32_32_1_5_U0_start_write),
    .m_axi_gmem0_AWVALID(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(1'b0),
    .m_axi_gmem0_AWADDR(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(1'b0),
    .m_axi_gmem0_WDATA(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(gmem0_ARREADY),
    .m_axi_gmem0_ARADDR(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(gmem0_RVALID),
    .m_axi_gmem0_RREADY(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(gmem0_RDATA),
    .m_axi_gmem0_RLAST(gmem0_RLAST),
    .m_axi_gmem0_RID(gmem0_RID),
    .m_axi_gmem0_RUSER(gmem0_RUSER),
    .m_axi_gmem0_RRESP(gmem0_RRESP),
    .m_axi_gmem0_BVALID(1'b0),
    .m_axi_gmem0_BREADY(Array2xfMat_8_0_32_32_1_5_U0_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(2'd0),
    .m_axi_gmem0_BID(1'd0),
    .m_axi_gmem0_BUSER(1'd0),
    .imgInput1_434_din(Array2xfMat_8_0_32_32_1_5_U0_imgInput1_434_din),
    .imgInput1_434_full_n(imgInput1_data_full_n),
    .imgInput1_434_write(Array2xfMat_8_0_32_32_1_5_U0_imgInput1_434_write),
    .srcPtr_dout(img_in1_c_dout),
    .srcPtr_empty_n(img_in1_c_empty_n),
    .srcPtr_read(Array2xfMat_8_0_32_32_1_5_U0_srcPtr_read),
    .dstMat_rows_dout(imgInput1_rows_c_dout),
    .dstMat_rows_empty_n(imgInput1_rows_c_empty_n),
    .dstMat_rows_read(Array2xfMat_8_0_32_32_1_5_U0_dstMat_rows_read),
    .dstMat_cols_dout(imgInput1_cols_c_dout),
    .dstMat_cols_empty_n(imgInput1_cols_c_empty_n),
    .dstMat_cols_read(Array2xfMat_8_0_32_32_1_5_U0_dstMat_cols_read),
    .dstMat_rows_out_din(Array2xfMat_8_0_32_32_1_5_U0_dstMat_rows_out_din),
    .dstMat_rows_out_full_n(imgInput1_rows_c11_full_n),
    .dstMat_rows_out_write(Array2xfMat_8_0_32_32_1_5_U0_dstMat_rows_out_write),
    .dstMat_cols_out_din(Array2xfMat_8_0_32_32_1_5_U0_dstMat_cols_out_din),
    .dstMat_cols_out_full_n(imgInput1_cols_c12_full_n),
    .dstMat_cols_out_write(Array2xfMat_8_0_32_32_1_5_U0_dstMat_cols_out_write)
);

arithm_accel_Array2xfMat_8_0_32_32_1_s Array2xfMat_8_0_32_32_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Array2xfMat_8_0_32_32_1_U0_ap_start),
    .ap_done(Array2xfMat_8_0_32_32_1_U0_ap_done),
    .ap_continue(Array2xfMat_8_0_32_32_1_U0_ap_continue),
    .ap_idle(Array2xfMat_8_0_32_32_1_U0_ap_idle),
    .ap_ready(Array2xfMat_8_0_32_32_1_U0_ap_ready),
    .m_axi_gmem0_AWVALID(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(1'b0),
    .m_axi_gmem0_AWADDR(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(1'b0),
    .m_axi_gmem0_WDATA(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(gmem1_ARREADY),
    .m_axi_gmem0_ARADDR(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(gmem1_RVALID),
    .m_axi_gmem0_RREADY(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(gmem1_RDATA),
    .m_axi_gmem0_RLAST(gmem1_RLAST),
    .m_axi_gmem0_RID(gmem1_RID),
    .m_axi_gmem0_RUSER(gmem1_RUSER),
    .m_axi_gmem0_RRESP(gmem1_RRESP),
    .m_axi_gmem0_BVALID(1'b0),
    .m_axi_gmem0_BREADY(Array2xfMat_8_0_32_32_1_U0_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(2'd0),
    .m_axi_gmem0_BID(1'd0),
    .m_axi_gmem0_BUSER(1'd0),
    .imgInput1_434_din(Array2xfMat_8_0_32_32_1_U0_imgInput1_434_din),
    .imgInput1_434_full_n(imgInput2_data_full_n),
    .imgInput1_434_write(Array2xfMat_8_0_32_32_1_U0_imgInput1_434_write),
    .srcPtr_dout(img_in2_c_dout),
    .srcPtr_empty_n(img_in2_c_empty_n),
    .srcPtr_read(Array2xfMat_8_0_32_32_1_U0_srcPtr_read),
    .p_read(imgInput2_rows_channel_dout),
    .p_read1(imgInput2_cols_channel_dout)
);

arithm_accel_absdiff_0_32_32_1_s absdiff_0_32_32_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(absdiff_0_32_32_1_U0_ap_start),
    .ap_done(absdiff_0_32_32_1_U0_ap_done),
    .ap_continue(absdiff_0_32_32_1_U0_ap_continue),
    .ap_idle(absdiff_0_32_32_1_U0_ap_idle),
    .ap_ready(absdiff_0_32_32_1_U0_ap_ready),
    .imgInput1_434_dout(imgInput1_data_dout),
    .imgInput1_434_empty_n(imgInput1_data_empty_n),
    .imgInput1_434_read(absdiff_0_32_32_1_U0_imgInput1_434_read),
    .imgInput2_435_dout(imgInput2_data_dout),
    .imgInput2_435_empty_n(imgInput2_data_empty_n),
    .imgInput2_435_read(absdiff_0_32_32_1_U0_imgInput2_435_read),
    .imgOutput_436_din(absdiff_0_32_32_1_U0_imgOutput_436_din),
    .imgOutput_436_full_n(imgOutput_data_full_n),
    .imgOutput_436_write(absdiff_0_32_32_1_U0_imgOutput_436_write),
    .p_src1_rows_dout(imgInput1_rows_c11_dout),
    .p_src1_rows_empty_n(imgInput1_rows_c11_empty_n),
    .p_src1_rows_read(absdiff_0_32_32_1_U0_p_src1_rows_read),
    .p_src1_cols_dout(imgInput1_cols_c12_dout),
    .p_src1_cols_empty_n(imgInput1_cols_c12_empty_n),
    .p_src1_cols_read(absdiff_0_32_32_1_U0_p_src1_cols_read)
);

arithm_accel_xfMat2Array_8_0_32_32_1_1_s xfMat2Array_8_0_32_32_1_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(xfMat2Array_8_0_32_32_1_1_U0_ap_start),
    .ap_done(xfMat2Array_8_0_32_32_1_1_U0_ap_done),
    .ap_continue(xfMat2Array_8_0_32_32_1_1_U0_ap_continue),
    .ap_idle(xfMat2Array_8_0_32_32_1_1_U0_ap_idle),
    .ap_ready(xfMat2Array_8_0_32_32_1_1_U0_ap_ready),
    .imgOutput_436_dout(imgOutput_data_dout),
    .imgOutput_436_empty_n(imgOutput_data_empty_n),
    .imgOutput_436_read(xfMat2Array_8_0_32_32_1_1_U0_imgOutput_436_read),
    .m_axi_gmem2_AWVALID(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWVALID),
    .m_axi_gmem2_AWREADY(gmem2_AWREADY),
    .m_axi_gmem2_AWADDR(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWADDR),
    .m_axi_gmem2_AWID(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWID),
    .m_axi_gmem2_AWLEN(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWLEN),
    .m_axi_gmem2_AWSIZE(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWSIZE),
    .m_axi_gmem2_AWBURST(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWBURST),
    .m_axi_gmem2_AWLOCK(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWLOCK),
    .m_axi_gmem2_AWCACHE(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWCACHE),
    .m_axi_gmem2_AWPROT(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWPROT),
    .m_axi_gmem2_AWQOS(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWQOS),
    .m_axi_gmem2_AWREGION(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWREGION),
    .m_axi_gmem2_AWUSER(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_AWUSER),
    .m_axi_gmem2_WVALID(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_WVALID),
    .m_axi_gmem2_WREADY(gmem2_WREADY),
    .m_axi_gmem2_WDATA(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_WDATA),
    .m_axi_gmem2_WSTRB(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_WSTRB),
    .m_axi_gmem2_WLAST(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_WLAST),
    .m_axi_gmem2_WID(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_WID),
    .m_axi_gmem2_WUSER(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_WUSER),
    .m_axi_gmem2_ARVALID(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_ARVALID),
    .m_axi_gmem2_ARREADY(1'b0),
    .m_axi_gmem2_ARADDR(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_ARADDR),
    .m_axi_gmem2_ARID(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_ARID),
    .m_axi_gmem2_ARLEN(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_ARLEN),
    .m_axi_gmem2_ARSIZE(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_ARSIZE),
    .m_axi_gmem2_ARBURST(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_ARBURST),
    .m_axi_gmem2_ARLOCK(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_ARLOCK),
    .m_axi_gmem2_ARCACHE(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_ARCACHE),
    .m_axi_gmem2_ARPROT(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_ARPROT),
    .m_axi_gmem2_ARQOS(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_ARQOS),
    .m_axi_gmem2_ARREGION(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_ARREGION),
    .m_axi_gmem2_ARUSER(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_ARUSER),
    .m_axi_gmem2_RVALID(1'b0),
    .m_axi_gmem2_RREADY(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_RREADY),
    .m_axi_gmem2_RDATA(8'd0),
    .m_axi_gmem2_RLAST(1'b0),
    .m_axi_gmem2_RID(1'd0),
    .m_axi_gmem2_RUSER(1'd0),
    .m_axi_gmem2_RRESP(2'd0),
    .m_axi_gmem2_BVALID(gmem2_BVALID),
    .m_axi_gmem2_BREADY(xfMat2Array_8_0_32_32_1_1_U0_m_axi_gmem2_BREADY),
    .m_axi_gmem2_BRESP(gmem2_BRESP),
    .m_axi_gmem2_BID(gmem2_BID),
    .m_axi_gmem2_BUSER(gmem2_BUSER),
    .srcMat_rows_dout(imgOutput_rows_c_dout),
    .srcMat_rows_empty_n(imgOutput_rows_c_empty_n),
    .srcMat_rows_read(xfMat2Array_8_0_32_32_1_1_U0_srcMat_rows_read),
    .srcMat_cols_dout(imgOutput_cols_c_dout),
    .srcMat_cols_empty_n(imgOutput_cols_c_empty_n),
    .srcMat_cols_read(xfMat2Array_8_0_32_32_1_1_U0_srcMat_cols_read),
    .dstPtr_dout(img_out_c_dout),
    .dstPtr_empty_n(img_out_c_empty_n),
    .dstPtr_read(xfMat2Array_8_0_32_32_1_1_U0_dstPtr_read)
);

arithm_accel_fifo_w32_d2_S_x1 imgInput1_rows_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_split1_proc22_U0_imgInput1_rows_out_din),
    .if_full_n(imgInput1_rows_c_full_n),
    .if_write(Block_split1_proc22_U0_imgInput1_rows_out_write),
    .if_dout(imgInput1_rows_c_dout),
    .if_empty_n(imgInput1_rows_c_empty_n),
    .if_read(Array2xfMat_8_0_32_32_1_5_U0_dstMat_rows_read)
);

arithm_accel_fifo_w32_d2_S_x1 imgInput1_cols_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_split1_proc22_U0_imgInput1_cols_out_din),
    .if_full_n(imgInput1_cols_c_full_n),
    .if_write(Block_split1_proc22_U0_imgInput1_cols_out_write),
    .if_dout(imgInput1_cols_c_dout),
    .if_empty_n(imgInput1_cols_c_empty_n),
    .if_read(Array2xfMat_8_0_32_32_1_5_U0_dstMat_cols_read)
);

arithm_accel_fifo_w32_d4_S_x imgOutput_rows_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_split1_proc22_U0_imgOutput_rows_out_din),
    .if_full_n(imgOutput_rows_c_full_n),
    .if_write(Block_split1_proc22_U0_imgOutput_rows_out_write),
    .if_dout(imgOutput_rows_c_dout),
    .if_empty_n(imgOutput_rows_c_empty_n),
    .if_read(xfMat2Array_8_0_32_32_1_1_U0_srcMat_rows_read)
);

arithm_accel_fifo_w32_d4_S_x imgOutput_cols_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_split1_proc22_U0_imgOutput_cols_out_din),
    .if_full_n(imgOutput_cols_c_full_n),
    .if_write(Block_split1_proc22_U0_imgOutput_cols_out_write),
    .if_dout(imgOutput_cols_c_dout),
    .if_empty_n(imgOutput_cols_c_empty_n),
    .if_read(xfMat2Array_8_0_32_32_1_1_U0_srcMat_cols_read)
);

arithm_accel_fifo_w64_d2_S_x img_in1_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_split1_proc22_U0_img_in1_out_din),
    .if_full_n(img_in1_c_full_n),
    .if_write(Block_split1_proc22_U0_img_in1_out_write),
    .if_dout(img_in1_c_dout),
    .if_empty_n(img_in1_c_empty_n),
    .if_read(Array2xfMat_8_0_32_32_1_5_U0_srcPtr_read)
);

arithm_accel_fifo_w64_d2_S_x img_in2_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_split1_proc22_U0_img_in2_out_din),
    .if_full_n(img_in2_c_full_n),
    .if_write(Block_split1_proc22_U0_img_in2_out_write),
    .if_dout(img_in2_c_dout),
    .if_empty_n(img_in2_c_empty_n),
    .if_read(Array2xfMat_8_0_32_32_1_U0_srcPtr_read)
);

arithm_accel_fifo_w64_d4_S_x0 img_out_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_split1_proc22_U0_img_out_out_din),
    .if_full_n(img_out_c_full_n),
    .if_write(Block_split1_proc22_U0_img_out_out_write),
    .if_dout(img_out_c_dout),
    .if_empty_n(img_out_c_empty_n),
    .if_read(xfMat2Array_8_0_32_32_1_1_U0_dstPtr_read)
);

arithm_accel_fifo_w32_d2_S_x1 imgInput2_rows_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_split1_proc22_U0_ap_return_0),
    .if_full_n(imgInput2_rows_channel_full_n),
    .if_write(ap_channel_done_imgInput2_rows_channel),
    .if_dout(imgInput2_rows_channel_dout),
    .if_empty_n(imgInput2_rows_channel_empty_n),
    .if_read(Array2xfMat_8_0_32_32_1_U0_ap_ready)
);

arithm_accel_fifo_w32_d2_S_x1 imgInput2_cols_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_split1_proc22_U0_ap_return_1),
    .if_full_n(imgInput2_cols_channel_full_n),
    .if_write(ap_channel_done_imgInput2_cols_channel),
    .if_dout(imgInput2_cols_channel_dout),
    .if_empty_n(imgInput2_cols_channel_empty_n),
    .if_read(Array2xfMat_8_0_32_32_1_U0_ap_ready)
);

arithm_accel_fifo_w8_d2_S_x0 imgInput1_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Array2xfMat_8_0_32_32_1_5_U0_imgInput1_434_din),
    .if_full_n(imgInput1_data_full_n),
    .if_write(Array2xfMat_8_0_32_32_1_5_U0_imgInput1_434_write),
    .if_dout(imgInput1_data_dout),
    .if_empty_n(imgInput1_data_empty_n),
    .if_read(absdiff_0_32_32_1_U0_imgInput1_434_read)
);

arithm_accel_fifo_w32_d2_S_x1 imgInput1_rows_c11_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Array2xfMat_8_0_32_32_1_5_U0_dstMat_rows_out_din),
    .if_full_n(imgInput1_rows_c11_full_n),
    .if_write(Array2xfMat_8_0_32_32_1_5_U0_dstMat_rows_out_write),
    .if_dout(imgInput1_rows_c11_dout),
    .if_empty_n(imgInput1_rows_c11_empty_n),
    .if_read(absdiff_0_32_32_1_U0_p_src1_rows_read)
);

arithm_accel_fifo_w32_d2_S_x1 imgInput1_cols_c12_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Array2xfMat_8_0_32_32_1_5_U0_dstMat_cols_out_din),
    .if_full_n(imgInput1_cols_c12_full_n),
    .if_write(Array2xfMat_8_0_32_32_1_5_U0_dstMat_cols_out_write),
    .if_dout(imgInput1_cols_c12_dout),
    .if_empty_n(imgInput1_cols_c12_empty_n),
    .if_read(absdiff_0_32_32_1_U0_p_src1_cols_read)
);

arithm_accel_fifo_w8_d2_S_x0 imgInput2_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Array2xfMat_8_0_32_32_1_U0_imgInput1_434_din),
    .if_full_n(imgInput2_data_full_n),
    .if_write(Array2xfMat_8_0_32_32_1_U0_imgInput1_434_write),
    .if_dout(imgInput2_data_dout),
    .if_empty_n(imgInput2_data_empty_n),
    .if_read(absdiff_0_32_32_1_U0_imgInput2_435_read)
);

arithm_accel_fifo_w8_d2_S_x0 imgOutput_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(absdiff_0_32_32_1_U0_imgOutput_436_din),
    .if_full_n(imgOutput_data_full_n),
    .if_write(absdiff_0_32_32_1_U0_imgOutput_436_write),
    .if_dout(imgOutput_data_dout),
    .if_empty_n(imgOutput_data_empty_n),
    .if_read(xfMat2Array_8_0_32_32_1_1_U0_imgOutput_436_read)
);

arithm_accel_start_for_xfMat2Array_8_0_32_32_1_1_U0 start_for_xfMat2Array_8_0_32_32_1_1_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xfMat2Array_8_0_32_32_1_1_U0_din),
    .if_full_n(start_for_xfMat2Array_8_0_32_32_1_1_U0_full_n),
    .if_write(Block_split1_proc22_U0_start_write),
    .if_dout(start_for_xfMat2Array_8_0_32_32_1_1_U0_dout),
    .if_empty_n(start_for_xfMat2Array_8_0_32_32_1_1_U0_empty_n),
    .if_read(xfMat2Array_8_0_32_32_1_1_U0_ap_ready)
);

arithm_accel_start_for_absdiff_0_32_32_1_U0 start_for_absdiff_0_32_32_1_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_absdiff_0_32_32_1_U0_din),
    .if_full_n(start_for_absdiff_0_32_32_1_U0_full_n),
    .if_write(Array2xfMat_8_0_32_32_1_5_U0_start_write),
    .if_dout(start_for_absdiff_0_32_32_1_U0_dout),
    .if_empty_n(start_for_absdiff_0_32_32_1_U0_empty_n),
    .if_read(absdiff_0_32_32_1_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Array2xfMat_8_0_32_32_1_5_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Array2xfMat_8_0_32_32_1_5_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Array2xfMat_8_0_32_32_1_5_U0_ap_ready <= ap_sync_Array2xfMat_8_0_32_32_1_5_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Array2xfMat_8_0_32_32_1_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Array2xfMat_8_0_32_32_1_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Array2xfMat_8_0_32_32_1_U0_ap_ready <= ap_sync_Array2xfMat_8_0_32_32_1_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Block_split1_proc22_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Block_split1_proc22_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Block_split1_proc22_U0_ap_ready <= ap_sync_Block_split1_proc22_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_imgInput2_cols_channel <= 1'b0;
    end else begin
        if (((Block_split1_proc22_U0_ap_done & Block_split1_proc22_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_imgInput2_cols_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_imgInput2_cols_channel <= ap_sync_channel_write_imgInput2_cols_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_imgInput2_rows_channel <= 1'b0;
    end else begin
        if (((Block_split1_proc22_U0_ap_done & Block_split1_proc22_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_imgInput2_rows_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_imgInput2_rows_channel <= ap_sync_channel_write_imgInput2_rows_channel;
        end
    end
end

assign Array2xfMat_8_0_32_32_1_5_U0_ap_continue = 1'b1;

assign Array2xfMat_8_0_32_32_1_5_U0_ap_start = ((ap_sync_reg_Array2xfMat_8_0_32_32_1_5_U0_ap_ready ^ 1'b1) & ap_start);

assign Array2xfMat_8_0_32_32_1_U0_ap_continue = 1'b1;

assign Array2xfMat_8_0_32_32_1_U0_ap_start = (imgInput2_rows_channel_empty_n & imgInput2_cols_channel_empty_n & (ap_sync_reg_Array2xfMat_8_0_32_32_1_U0_ap_ready ^ 1'b1) & ap_start);

assign Array2xfMat_8_0_32_32_1_U0_start_full_n = 1'b1;

assign Array2xfMat_8_0_32_32_1_U0_start_write = 1'b0;

assign Block_split1_proc22_U0_ap_continue = (ap_sync_channel_write_imgInput2_rows_channel & ap_sync_channel_write_imgInput2_cols_channel);

assign Block_split1_proc22_U0_ap_start = ((ap_sync_reg_Block_split1_proc22_U0_ap_ready ^ 1'b1) & ap_start);

assign absdiff_0_32_32_1_U0_ap_continue = 1'b1;

assign absdiff_0_32_32_1_U0_ap_start = start_for_absdiff_0_32_32_1_U0_empty_n;

assign absdiff_0_32_32_1_U0_start_full_n = 1'b1;

assign absdiff_0_32_32_1_U0_start_write = 1'b0;

assign ap_channel_done_imgInput2_cols_channel = ((ap_sync_reg_channel_write_imgInput2_cols_channel ^ 1'b1) & Block_split1_proc22_U0_ap_done);

assign ap_channel_done_imgInput2_rows_channel = ((ap_sync_reg_channel_write_imgInput2_rows_channel ^ 1'b1) & Block_split1_proc22_U0_ap_done);

assign ap_done = xfMat2Array_8_0_32_32_1_1_U0_ap_done;

assign ap_idle = (xfMat2Array_8_0_32_32_1_1_U0_ap_idle & (imgInput2_cols_channel_empty_n ^ 1'b1) & (imgInput2_rows_channel_empty_n ^ 1'b1) & absdiff_0_32_32_1_U0_ap_idle & Block_split1_proc22_U0_ap_idle & Array2xfMat_8_0_32_32_1_U0_ap_idle & Array2xfMat_8_0_32_32_1_5_U0_ap_idle);

assign ap_ready = ap_sync_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_Array2xfMat_8_0_32_32_1_5_U0_ap_ready = (ap_sync_reg_Array2xfMat_8_0_32_32_1_5_U0_ap_ready | Array2xfMat_8_0_32_32_1_5_U0_ap_ready);

assign ap_sync_Array2xfMat_8_0_32_32_1_U0_ap_ready = (ap_sync_reg_Array2xfMat_8_0_32_32_1_U0_ap_ready | Array2xfMat_8_0_32_32_1_U0_ap_ready);

assign ap_sync_Block_split1_proc22_U0_ap_ready = (ap_sync_reg_Block_split1_proc22_U0_ap_ready | Block_split1_proc22_U0_ap_ready);

assign ap_sync_channel_write_imgInput2_cols_channel = ((imgInput2_cols_channel_full_n & ap_channel_done_imgInput2_cols_channel) | ap_sync_reg_channel_write_imgInput2_cols_channel);

assign ap_sync_channel_write_imgInput2_rows_channel = ((imgInput2_rows_channel_full_n & ap_channel_done_imgInput2_rows_channel) | ap_sync_reg_channel_write_imgInput2_rows_channel);

assign ap_sync_continue = 1'b1;

assign ap_sync_done = xfMat2Array_8_0_32_32_1_1_U0_ap_done;

assign ap_sync_ready = (ap_sync_Block_split1_proc22_U0_ap_ready & ap_sync_Array2xfMat_8_0_32_32_1_U0_ap_ready & ap_sync_Array2xfMat_8_0_32_32_1_5_U0_ap_ready);

assign start_for_absdiff_0_32_32_1_U0_din = 1'b1;

assign start_for_xfMat2Array_8_0_32_32_1_1_U0_din = 1'b1;

assign xfMat2Array_8_0_32_32_1_1_U0_ap_continue = 1'b1;

assign xfMat2Array_8_0_32_32_1_1_U0_ap_start = start_for_xfMat2Array_8_0_32_32_1_1_U0_empty_n;

assign xfMat2Array_8_0_32_32_1_1_U0_start_full_n = 1'b1;

assign xfMat2Array_8_0_32_32_1_1_U0_start_write = 1'b0;


// synthesis translate_off
`include "arithm_accel_hls_deadlock_detector.vh"
// synthesis translate_on

endmodule //arithm_accel

