# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/vivado_prj/base/project_1/project_1.srcs/sources_1/bd/base/ip/base_vtc_out_0/base_vtc_out_0.xci
# IP: The module: 'base_vtc_out_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_prj/base/project_1/project_1.srcs/sources_1/bd/base/ip/base_vtc_out_0/base_vtc_out_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_vtc_out_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/vivado_prj/base/project_1/project_1.srcs/sources_1/bd/base/ip/base_vtc_out_0/base_vtc_out_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_vtc_out_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/vivado_prj/base/project_1/project_1.srcs/sources_1/bd/base/ip/base_vtc_out_0/base_vtc_out_0.xci
# IP: The module: 'base_vtc_out_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_prj/base/project_1/project_1.srcs/sources_1/bd/base/ip/base_vtc_out_0/base_vtc_out_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_vtc_out_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/vivado_prj/base/project_1/project_1.srcs/sources_1/bd/base/ip/base_vtc_out_0/base_vtc_out_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_vtc_out_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
