# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/GT/base/project_1/project_1.srcs/sources_1/bd/base/ip/base_pixel_unpack_0/base_pixel_unpack_0.xci
# IP: The module: 'base_pixel_unpack_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/GT/base/project_1/project_1.srcs/sources_1/bd/base/ip/base_pixel_unpack_0/constraints/pixel_unpack_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_pixel_unpack_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/GT/base/project_1/project_1.srcs/sources_1/bd/base/ip/base_pixel_unpack_0/base_pixel_unpack_0.xci
# IP: The module: 'base_pixel_unpack_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/GT/base/project_1/project_1.srcs/sources_1/bd/base/ip/base_pixel_unpack_0/constraints/pixel_unpack_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_pixel_unpack_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
