# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/vivado_prj/base/project_1/project_1.srcs/sources_1/bd/base/ip/base_auto_pc_19/base_auto_pc_19.xci
# IP: The module: 'base_auto_pc_19' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_prj/base/project_1/project_1.srcs/sources_1/bd/base/ip/base_auto_pc_19/base_auto_pc_19_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_auto_pc_19'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/vivado_prj/base/project_1/project_1.srcs/sources_1/bd/base/ip/base_auto_pc_19/base_auto_pc_19.xci
# IP: The module: 'base_auto_pc_19' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_prj/base/project_1/project_1.srcs/sources_1/bd/base/ip/base_auto_pc_19/base_auto_pc_19_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_auto_pc_19'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
