# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/GT/base/project_1/project_1.srcs/sources_1/bd/base/ip/base_axi_gpio_hdmiin_0/base_axi_gpio_hdmiin_0.xci
# IP: The module: 'base_axi_gpio_hdmiin_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/GT/base/project_1/project_1.srcs/sources_1/bd/base/ip/base_axi_gpio_hdmiin_0/base_axi_gpio_hdmiin_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_gpio_hdmiin_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/GT/base/project_1/project_1.srcs/sources_1/bd/base/ip/base_axi_gpio_hdmiin_0/base_axi_gpio_hdmiin_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_gpio_hdmiin_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/GT/base/project_1/project_1.srcs/sources_1/bd/base/ip/base_axi_gpio_hdmiin_0/base_axi_gpio_hdmiin_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_gpio_hdmiin_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/GT/base/project_1/project_1.srcs/sources_1/bd/base/ip/base_axi_gpio_hdmiin_0/base_axi_gpio_hdmiin_0.xci
# IP: The module: 'base_axi_gpio_hdmiin_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/GT/base/project_1/project_1.srcs/sources_1/bd/base/ip/base_axi_gpio_hdmiin_0/base_axi_gpio_hdmiin_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_gpio_hdmiin_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/GT/base/project_1/project_1.srcs/sources_1/bd/base/ip/base_axi_gpio_hdmiin_0/base_axi_gpio_hdmiin_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_gpio_hdmiin_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/GT/base/project_1/project_1.srcs/sources_1/bd/base/ip/base_axi_gpio_hdmiin_0/base_axi_gpio_hdmiin_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_gpio_hdmiin_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
