// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dilation_accel_xfdilate_32_32_1_0_1_0_33_3_3_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_mat_419_dout,
        in_mat_419_empty_n,
        in_mat_419_read,
        out_mat_420_din,
        out_mat_420_full_n,
        out_mat_420_write,
        img_height,
        img_width,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_pp1_stage0 = 10'd8;
parameter    ap_ST_fsm_state6 = 10'd16;
parameter    ap_ST_fsm_state7 = 10'd32;
parameter    ap_ST_fsm_state8 = 10'd64;
parameter    ap_ST_fsm_state9 = 10'd128;
parameter    ap_ST_fsm_pp3_stage0 = 10'd256;
parameter    ap_ST_fsm_state18 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] in_mat_419_dout;
input   in_mat_419_empty_n;
output   in_mat_419_read;
output  [7:0] out_mat_420_din;
input   out_mat_420_full_n;
output   out_mat_420_write;
input  [15:0] img_height;
input  [15:0] img_width;
input  [7:0] p_read;
input  [7:0] p_read1;
input  [7:0] p_read2;
input  [7:0] p_read3;
input  [7:0] p_read4;
input  [7:0] p_read5;
input  [7:0] p_read6;
input  [7:0] p_read7;
input  [7:0] p_read8;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_mat_419_read;
reg out_mat_420_write;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    in_mat_419_blk_n;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter1;
wire    ap_block_pp1_stage0;
reg   [0:0] icmp_ln878_reg_1095;
wire    ap_CS_fsm_pp3_stage0;
reg    ap_enable_reg_pp3_iter1;
wire    ap_block_pp3_stage0;
reg   [0:0] icmp_ln878_4_reg_1193;
reg   [0:0] icmp_ln878_5_reg_1197;
reg   [0:0] cmp_i_i115_i_reg_1170;
reg    out_mat_420_blk_n;
reg    ap_enable_reg_pp3_iter7;
reg   [0:0] icmp_ln882_reg_1221;
reg   [0:0] icmp_ln882_reg_1221_pp3_iter6_reg;
reg   [12:0] i_col_046_0_reg_338;
reg   [12:0] col_V_reg_406;
reg   [12:0] col_V_reg_406_pp3_iter1_reg;
wire    ap_block_state10_pp3_stage0_iter0;
reg    ap_predicate_op146_read_state11;
reg    ap_block_state11_pp3_stage0_iter1;
wire    ap_block_state12_pp3_stage0_iter2;
wire    ap_block_state13_pp3_stage0_iter3;
wire    ap_block_state14_pp3_stage0_iter4;
wire    ap_block_state15_pp3_stage0_iter5;
wire    ap_block_state16_pp3_stage0_iter6;
reg    ap_block_state17_pp3_stage0_iter7;
reg    ap_block_pp3_stage0_11001;
reg   [7:0] src_buf_V_0_0_reg_430;
reg   [7:0] p_Val2_s_reg_442;
reg   [7:0] src_buf_V_1_0_reg_465;
reg   [7:0] p_Val2_1_reg_477;
reg   [7:0] p_Val2_2_reg_500;
reg   [7:0] src_buf_V_2_0_reg_511;
wire   [13:0] empty_fu_554_p1;
reg   [13:0] empty_reg_1062;
wire   [1:0] init_row_ind_fu_558_p2;
wire    ap_CS_fsm_state2;
reg   [12:0] row_ind_V_0_0_load_reg_1072;
reg   [12:0] row_ind_V_1_0_load_reg_1077;
reg   [12:0] row_ind_V_2_0_load_reg_1082;
wire   [12:0] add_ln691_fu_598_p2;
reg   [12:0] add_ln691_reg_1090;
reg    ap_enable_reg_pp1_iter0;
wire    ap_block_state4_pp1_stage0_iter0;
reg    ap_block_state5_pp1_stage0_iter1;
reg    ap_block_pp1_stage0_11001;
wire   [0:0] icmp_ln878_fu_608_p2;
wire   [12:0] add_ln691_1_fu_618_p2;
wire    ap_CS_fsm_state7;
wire   [16:0] op2_assign_fu_641_p2;
reg   [16:0] op2_assign_reg_1107;
wire    ap_CS_fsm_state8;
wire   [13:0] add_ln1616_fu_647_p2;
reg   [13:0] add_ln1616_reg_1112;
wire   [0:0] icmp_ln878_2_fu_662_p2;
reg   [0:0] icmp_ln878_2_reg_1117;
wire   [0:0] tobool_i_i_fu_668_p2;
reg   [0:0] tobool_i_i_reg_1121;
wire   [0:0] tobool_i_i_160_fu_673_p2;
reg   [0:0] tobool_i_i_160_reg_1126;
wire   [0:0] tobool_i_i_269_fu_678_p2;
reg   [0:0] tobool_i_i_269_reg_1131;
wire   [0:0] tobool_i_i_1_fu_683_p2;
reg   [0:0] tobool_i_i_1_reg_1136;
wire   [0:0] tobool_i_i_1_1_fu_688_p2;
reg   [0:0] tobool_i_i_1_1_reg_1141;
wire   [0:0] tobool_i_i_1_2_fu_693_p2;
reg   [0:0] tobool_i_i_1_2_reg_1146;
wire   [0:0] tobool_i_i_2_fu_698_p2;
reg   [0:0] tobool_i_i_2_reg_1151;
wire   [0:0] tobool_i_i_2_1_fu_703_p2;
reg   [0:0] tobool_i_i_2_1_reg_1156;
wire   [0:0] tobool_i_i_2_2_fu_708_p2;
reg   [0:0] tobool_i_i_2_2_reg_1161;
wire   [0:0] icmp_ln878_3_fu_721_p2;
wire    ap_CS_fsm_state9;
wire   [0:0] cmp_i_i115_i_fu_726_p2;
wire   [1:0] trunc_ln123_fu_731_p1;
reg   [1:0] trunc_ln123_reg_1174;
wire   [1:0] trunc_ln136_fu_735_p1;
reg   [1:0] trunc_ln136_reg_1178;
wire   [1:0] trunc_ln136_1_fu_739_p1;
reg   [1:0] trunc_ln136_1_reg_1183;
wire   [12:0] col_V_1_fu_743_p2;
reg   [12:0] col_V_1_reg_1188;
reg    ap_enable_reg_pp3_iter0;
wire   [0:0] icmp_ln878_4_fu_757_p2;
reg   [0:0] icmp_ln878_4_reg_1193_pp3_iter1_reg;
reg   [0:0] icmp_ln878_4_reg_1193_pp3_iter2_reg;
reg   [0:0] icmp_ln878_4_reg_1193_pp3_iter3_reg;
reg   [0:0] icmp_ln878_4_reg_1193_pp3_iter4_reg;
reg   [0:0] icmp_ln878_4_reg_1193_pp3_iter5_reg;
reg   [0:0] icmp_ln878_4_reg_1193_pp3_iter6_reg;
wire   [0:0] icmp_ln878_5_fu_762_p2;
reg   [0:0] icmp_ln878_5_reg_1197_pp3_iter1_reg;
reg   [0:0] icmp_ln878_5_reg_1197_pp3_iter2_reg;
wire   [0:0] icmp_ln882_fu_788_p2;
reg   [0:0] icmp_ln882_reg_1221_pp3_iter3_reg;
reg   [0:0] icmp_ln882_reg_1221_pp3_iter4_reg;
reg   [0:0] icmp_ln882_reg_1221_pp3_iter5_reg;
wire   [7:0] buf_cop_V_0_fu_794_p5;
wire   [7:0] tmp_fu_805_p5;
wire   [7:0] src_buf_V_0_1_xfExtractPixels_1_1_0_s_fu_536_ap_return;
reg   [7:0] src_buf_V_0_1_reg_1235;
reg    ap_enable_reg_pp3_iter4;
wire   [7:0] max_V_2_fu_858_p3;
reg   [7:0] max_V_2_reg_1240;
wire   [7:0] src_buf_V_1_1_xfExtractPixels_1_1_0_s_fu_542_ap_return;
reg   [7:0] src_buf_V_1_1_reg_1247;
reg    ap_enable_reg_pp3_iter5;
wire   [7:0] max_V_4_fu_897_p3;
reg   [7:0] max_V_4_reg_1253;
wire   [0:0] icmp_ln886_4_fu_904_p2;
reg   [0:0] icmp_ln886_4_reg_1259;
wire   [7:0] src_buf_V_2_1_xfExtractPixels_1_1_0_s_fu_548_ap_return;
reg   [7:0] src_buf_V_2_1_reg_1264;
reg    ap_enable_reg_pp3_iter6;
wire   [7:0] max_V_7_fu_956_p3;
reg   [7:0] max_V_7_reg_1271;
wire   [12:0] row_V_1_fu_980_p2;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state3;
reg    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state4;
reg    ap_block_pp3_stage0_subdone;
reg    ap_condition_pp3_flush_enable;
reg    ap_enable_reg_pp3_iter2;
reg    ap_enable_reg_pp3_iter3;
reg    ap_condition_pp3_exit_iter6_state16;
wire   [4:0] buf_V_0_address0;
reg    buf_V_0_ce0;
wire   [7:0] buf_V_0_q0;
reg   [4:0] buf_V_0_address1;
reg    buf_V_0_ce1;
reg    buf_V_0_we1;
reg   [7:0] buf_V_0_d1;
wire   [4:0] buf_V_1_address0;
reg    buf_V_1_ce0;
wire   [7:0] buf_V_1_q0;
reg   [4:0] buf_V_1_address1;
reg    buf_V_1_ce1;
reg    buf_V_1_we1;
reg   [7:0] buf_V_1_d1;
wire   [4:0] buf_V_2_address0;
reg    buf_V_2_ce0;
wire   [7:0] buf_V_2_q0;
reg   [4:0] buf_V_2_address1;
reg    buf_V_2_ce1;
reg    buf_V_2_we1;
reg   [7:0] buf_V_2_d1;
wire    src_buf_V_0_1_xfExtractPixels_1_1_0_s_fu_536_ap_ready;
wire    src_buf_V_1_1_xfExtractPixels_1_1_0_s_fu_542_ap_ready;
wire    src_buf_V_2_1_xfExtractPixels_1_1_0_s_fu_548_ap_ready;
wire   [1:0] ap_phi_mux_row_ind_V_1_phi_fu_331_p4;
reg   [1:0] row_ind_V_1_reg_327;
wire   [0:0] icmp_ln259_fu_573_p2;
reg   [12:0] ap_phi_mux_i_col_046_0_phi_fu_342_p4;
reg   [12:0] i_col_V_0_reg_350;
wire   [0:0] icmp_ln878_1_fu_628_p2;
wire    ap_CS_fsm_state6;
reg   [12:0] row_ind_V_2_reg_361;
reg   [12:0] row_ind_V_0_reg_382;
reg   [12:0] row_ind_V_1_1_reg_371;
reg   [12:0] row_V_reg_394;
reg   [12:0] ap_phi_mux_col_V_phi_fu_410_p4;
wire   [7:0] ap_phi_reg_pp3_iter0_arrayidx396_i179246_load_0_2_reg_418;
reg   [7:0] ap_phi_reg_pp3_iter1_arrayidx396_i179246_load_0_2_reg_418;
reg   [7:0] ap_phi_reg_pp3_iter2_arrayidx396_i179246_load_0_2_reg_418;
reg   [7:0] ap_phi_reg_pp3_iter3_arrayidx396_i179246_load_0_2_reg_418;
reg   [7:0] ap_phi_mux_src_buf_V_0_0_phi_fu_434_p4;
reg   [7:0] ap_phi_mux_p_Val2_s_phi_fu_446_p4;
wire   [7:0] ap_phi_reg_pp3_iter0_buf_cop_V_0_0_reg_454;
reg   [7:0] ap_phi_reg_pp3_iter1_buf_cop_V_0_0_reg_454;
reg   [7:0] ap_phi_reg_pp3_iter2_buf_cop_V_0_0_reg_454;
reg   [7:0] ap_phi_reg_pp3_iter3_buf_cop_V_0_0_reg_454;
reg   [7:0] ap_phi_reg_pp3_iter4_buf_cop_V_0_0_reg_454;
reg   [7:0] ap_phi_mux_src_buf_V_1_0_phi_fu_469_p4;
reg   [7:0] ap_phi_mux_p_Val2_1_phi_fu_481_p4;
wire   [7:0] ap_phi_reg_pp3_iter0_buf_cop_V_1_reg_489;
reg   [7:0] ap_phi_reg_pp3_iter1_buf_cop_V_1_reg_489;
reg   [7:0] ap_phi_reg_pp3_iter2_buf_cop_V_1_reg_489;
reg   [7:0] ap_phi_reg_pp3_iter3_buf_cop_V_1_reg_489;
reg   [7:0] ap_phi_reg_pp3_iter4_buf_cop_V_1_reg_489;
reg   [7:0] ap_phi_reg_pp3_iter5_buf_cop_V_1_reg_489;
reg   [7:0] ap_phi_mux_p_Val2_2_phi_fu_504_p4;
reg   [7:0] ap_phi_mux_src_buf_V_2_0_phi_fu_516_p4;
wire   [7:0] ap_phi_reg_pp3_iter0_buf_cop_V_2_reg_524;
reg   [7:0] ap_phi_reg_pp3_iter1_buf_cop_V_2_reg_524;
reg   [7:0] ap_phi_reg_pp3_iter2_buf_cop_V_2_reg_524;
reg   [7:0] ap_phi_reg_pp3_iter3_buf_cop_V_2_reg_524;
reg   [7:0] ap_phi_reg_pp3_iter4_buf_cop_V_2_reg_524;
reg   [7:0] ap_phi_reg_pp3_iter5_buf_cop_V_2_reg_524;
reg   [7:0] ap_phi_reg_pp3_iter6_buf_cop_V_2_reg_524;
wire   [63:0] zext_ln534_fu_613_p1;
wire   [63:0] zext_ln534_1_fu_633_p1;
wire   [63:0] zext_ln534_3_fu_767_p1;
wire   [63:0] zext_ln534_2_fu_774_p1;
wire   [63:0] zext_ln1616_fu_781_p1;
reg   [12:0] row_ind_V_0_0_fu_114;
wire   [12:0] zext_ln301_fu_579_p1;
reg   [12:0] row_ind_V_1_0_fu_118;
reg   [12:0] row_ind_V_2_0_fu_122;
reg    ap_block_pp3_stage0_01001;
wire   [15:0] zext_ln878_fu_604_p1;
wire   [15:0] zext_ln878_1_fu_624_p1;
wire   [16:0] img_height_cast_fu_638_p1;
wire   [15:0] tmp_1_fu_652_p4;
wire   [16:0] zext_ln878_3_fu_717_p1;
wire   [15:0] zext_ln878_2_fu_713_p1;
wire   [13:0] zext_ln878_5_fu_753_p1;
wire   [15:0] zext_ln878_4_fu_749_p1;
wire   [7:0] ret_fu_816_p3;
wire   [0:0] icmp_ln886_fu_823_p2;
wire   [7:0] select_ln56_fu_829_p3;
wire   [7:0] max_V_1_fu_837_p3;
wire   [0:0] icmp_ln886_1_fu_844_p2;
wire   [7:0] select_ln56_1_fu_850_p3;
wire   [0:0] icmp_ln886_2_fu_865_p2;
wire   [7:0] select_ln56_2_fu_870_p3;
wire   [7:0] max_V_3_fu_877_p3;
wire   [0:0] icmp_ln886_3_fu_883_p2;
wire   [7:0] select_ln56_3_fu_889_p3;
wire   [7:0] select_ln56_4_fu_910_p3;
wire   [7:0] max_V_5_fu_915_p3;
wire   [0:0] icmp_ln886_5_fu_921_p2;
wire   [7:0] select_ln56_5_fu_927_p3;
wire   [7:0] max_V_6_fu_935_p3;
wire   [0:0] icmp_ln886_6_fu_942_p2;
wire   [7:0] select_ln56_6_fu_948_p3;
wire   [0:0] icmp_ln886_7_fu_963_p2;
wire   [7:0] select_ln56_7_fu_967_p3;
reg   [9:0] ap_NS_fsm;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
reg    ap_idle_pp3;
wire    ap_enable_pp3;
reg    ap_condition_486;
reg    ap_condition_258;
reg    ap_condition_86;
reg    ap_condition_279;
reg    ap_condition_950;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp3_iter1 = 1'b0;
#0 ap_enable_reg_pp3_iter7 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp3_iter0 = 1'b0;
#0 ap_enable_reg_pp3_iter4 = 1'b0;
#0 ap_enable_reg_pp3_iter5 = 1'b0;
#0 ap_enable_reg_pp3_iter6 = 1'b0;
#0 ap_enable_reg_pp3_iter2 = 1'b0;
#0 ap_enable_reg_pp3_iter3 = 1'b0;
end

dilation_accel_xfdilate_32_32_1_0_1_0_33_3_3_s_buf_V_0 #(
    .DataWidth( 8 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
buf_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_V_0_address0),
    .ce0(buf_V_0_ce0),
    .q0(buf_V_0_q0),
    .address1(buf_V_0_address1),
    .ce1(buf_V_0_ce1),
    .we1(buf_V_0_we1),
    .d1(buf_V_0_d1)
);

dilation_accel_xfdilate_32_32_1_0_1_0_33_3_3_s_buf_V_0 #(
    .DataWidth( 8 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
buf_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_V_1_address0),
    .ce0(buf_V_1_ce0),
    .q0(buf_V_1_q0),
    .address1(buf_V_1_address1),
    .ce1(buf_V_1_ce1),
    .we1(buf_V_1_we1),
    .d1(buf_V_1_d1)
);

dilation_accel_xfdilate_32_32_1_0_1_0_33_3_3_s_buf_V_0 #(
    .DataWidth( 8 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
buf_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_V_2_address0),
    .ce0(buf_V_2_ce0),
    .q0(buf_V_2_q0),
    .address1(buf_V_2_address1),
    .ce1(buf_V_2_ce1),
    .we1(buf_V_2_we1),
    .d1(buf_V_2_d1)
);

dilation_accel_xfExtractPixels_1_1_0_s src_buf_V_0_1_xfExtractPixels_1_1_0_s_fu_536(
    .ap_ready(src_buf_V_0_1_xfExtractPixels_1_1_0_s_fu_536_ap_ready),
    .p_read1(ap_phi_reg_pp3_iter4_buf_cop_V_0_0_reg_454),
    .ap_return(src_buf_V_0_1_xfExtractPixels_1_1_0_s_fu_536_ap_return)
);

dilation_accel_xfExtractPixels_1_1_0_s src_buf_V_1_1_xfExtractPixels_1_1_0_s_fu_542(
    .ap_ready(src_buf_V_1_1_xfExtractPixels_1_1_0_s_fu_542_ap_ready),
    .p_read1(ap_phi_reg_pp3_iter5_buf_cop_V_1_reg_489),
    .ap_return(src_buf_V_1_1_xfExtractPixels_1_1_0_s_fu_542_ap_return)
);

dilation_accel_xfExtractPixels_1_1_0_s src_buf_V_2_1_xfExtractPixels_1_1_0_s_fu_548(
    .ap_ready(src_buf_V_2_1_xfExtractPixels_1_1_0_s_fu_548_ap_ready),
    .p_read1(ap_phi_reg_pp3_iter6_buf_cop_V_2_reg_524),
    .ap_return(src_buf_V_2_1_xfExtractPixels_1_1_0_s_fu_548_ap_return)
);

dilation_accel_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_32_8_1_1_U73(
    .din0(buf_V_0_q0),
    .din1(buf_V_1_q0),
    .din2(buf_V_2_q0),
    .din3(trunc_ln136_reg_1178),
    .dout(buf_cop_V_0_fu_794_p5)
);

dilation_accel_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_32_8_1_1_U74(
    .din0(buf_V_0_q0),
    .din1(buf_V_1_q0),
    .din2(buf_V_2_q0),
    .din3(trunc_ln136_1_reg_1183),
    .dout(tmp_fu_805_p5)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b1 == ap_condition_pp1_exit_iter0_state4))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state4))) begin
            ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state4);
        end else if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp1_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp3_flush_enable)) begin
            ap_enable_reg_pp3_iter0 <= 1'b0;
        end else if (((icmp_ln878_3_fu_721_p2 == 1'd1) & (icmp_ln878_2_reg_1117 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
            ap_enable_reg_pp3_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter1 <= ap_enable_reg_pp3_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter2 <= ap_enable_reg_pp3_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter3 <= ap_enable_reg_pp3_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter4 <= ap_enable_reg_pp3_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter5 <= ap_enable_reg_pp3_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter6 <= ap_enable_reg_pp3_iter5;
        end else if ((((1'b0 == ap_block_pp3_stage0_subdone) & (ap_enable_reg_pp3_iter5 == 1'b0) & (1'b1 == ap_condition_pp3_exit_iter6_state16)) | ((icmp_ln878_3_fu_721_p2 == 1'd1) & (icmp_ln878_2_reg_1117 == 1'd0) & (1'b1 == ap_CS_fsm_state9)))) begin
            ap_enable_reg_pp3_iter6 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter7 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp3_stage0_subdone) & (1'b1 == ap_condition_pp3_exit_iter6_state16))) begin
            ap_enable_reg_pp3_iter7 <= ap_enable_reg_pp3_iter5;
        end else if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter7 <= ap_enable_reg_pp3_iter6;
        end else if (((icmp_ln878_3_fu_721_p2 == 1'd1) & (icmp_ln878_2_reg_1117 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
            ap_enable_reg_pp3_iter7 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_258)) begin
        if ((1'b1 == ap_condition_486)) begin
            ap_phi_reg_pp3_iter1_arrayidx396_i179246_load_0_2_reg_418 <= 8'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp3_iter1_arrayidx396_i179246_load_0_2_reg_418 <= ap_phi_reg_pp3_iter0_arrayidx396_i179246_load_0_2_reg_418;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_258)) begin
        if (((icmp_ln878_5_fu_762_p2 == 1'd0) & (icmp_ln878_4_fu_757_p2 == 1'd1))) begin
            ap_phi_reg_pp3_iter1_buf_cop_V_0_0_reg_454 <= 8'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp3_iter1_buf_cop_V_0_0_reg_454 <= ap_phi_reg_pp3_iter0_buf_cop_V_0_0_reg_454;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_258)) begin
        if (((icmp_ln878_5_fu_762_p2 == 1'd0) & (icmp_ln878_4_fu_757_p2 == 1'd1))) begin
            ap_phi_reg_pp3_iter1_buf_cop_V_1_reg_489 <= 8'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp3_iter1_buf_cop_V_1_reg_489 <= ap_phi_reg_pp3_iter0_buf_cop_V_1_reg_489;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_258)) begin
        if (((icmp_ln878_5_fu_762_p2 == 1'd0) & (icmp_ln878_4_fu_757_p2 == 1'd1))) begin
            ap_phi_reg_pp3_iter1_buf_cop_V_2_reg_524 <= 8'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp3_iter1_buf_cop_V_2_reg_524 <= ap_phi_reg_pp3_iter0_buf_cop_V_2_reg_524;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_279)) begin
        if ((1'b1 == ap_condition_86)) begin
            ap_phi_reg_pp3_iter2_arrayidx396_i179246_load_0_2_reg_418 <= in_mat_419_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp3_iter2_arrayidx396_i179246_load_0_2_reg_418 <= ap_phi_reg_pp3_iter1_arrayidx396_i179246_load_0_2_reg_418;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter3 == 1'b1))) begin
        if (((icmp_ln878_5_reg_1197_pp3_iter2_reg == 1'd1) & (icmp_ln878_4_reg_1193_pp3_iter2_reg == 1'd1))) begin
            ap_phi_reg_pp3_iter4_buf_cop_V_0_0_reg_454 <= buf_cop_V_0_fu_794_p5;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp3_iter4_buf_cop_V_0_0_reg_454 <= ap_phi_reg_pp3_iter3_buf_cop_V_0_0_reg_454;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter3 == 1'b1))) begin
        if (((icmp_ln878_5_reg_1197_pp3_iter2_reg == 1'd1) & (icmp_ln878_4_reg_1193_pp3_iter2_reg == 1'd1))) begin
            ap_phi_reg_pp3_iter4_buf_cop_V_1_reg_489 <= tmp_fu_805_p5;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp3_iter4_buf_cop_V_1_reg_489 <= ap_phi_reg_pp3_iter3_buf_cop_V_1_reg_489;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter3 == 1'b1))) begin
        if (((icmp_ln878_5_reg_1197_pp3_iter2_reg == 1'd1) & (icmp_ln878_4_reg_1193_pp3_iter2_reg == 1'd1))) begin
            ap_phi_reg_pp3_iter4_buf_cop_V_2_reg_524 <= ap_phi_reg_pp3_iter3_arrayidx396_i179246_load_0_2_reg_418;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp3_iter4_buf_cop_V_2_reg_524 <= ap_phi_reg_pp3_iter3_buf_cop_V_2_reg_524;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln878_4_reg_1193 == 1'd1) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        col_V_reg_406 <= col_V_1_reg_1188;
    end else if (((icmp_ln878_3_fu_721_p2 == 1'd1) & (icmp_ln878_2_reg_1117 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        col_V_reg_406 <= 13'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_col_046_0_reg_338 <= 13'd0;
    end else if (((icmp_ln878_reg_1095 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        i_col_046_0_reg_338 <= add_ln691_reg_1090;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        i_col_V_0_reg_350 <= 13'd0;
    end else if (((icmp_ln878_1_fu_628_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        i_col_V_0_reg_350 <= add_ln691_1_fu_618_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter6 == 1'b1) & (icmp_ln878_4_reg_1193_pp3_iter5_reg == 1'd1))) begin
        p_Val2_1_reg_477 <= src_buf_V_1_0_reg_465;
    end else if (((icmp_ln878_3_fu_721_p2 == 1'd1) & (icmp_ln878_2_reg_1117 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        p_Val2_1_reg_477 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp3_iter7 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln878_4_reg_1193_pp3_iter6_reg == 1'd1))) begin
        p_Val2_2_reg_500 <= src_buf_V_2_0_reg_511;
    end else if (((icmp_ln878_3_fu_721_p2 == 1'd1) & (icmp_ln878_2_reg_1117 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        p_Val2_2_reg_500 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter5 == 1'b1) & (icmp_ln878_4_reg_1193_pp3_iter4_reg == 1'd1))) begin
        p_Val2_s_reg_442 <= src_buf_V_0_0_reg_430;
    end else if (((icmp_ln878_3_fu_721_p2 == 1'd1) & (icmp_ln878_2_reg_1117 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        p_Val2_s_reg_442 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        row_V_reg_394 <= row_V_1_fu_980_p2;
    end else if (((icmp_ln878_2_fu_662_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        row_V_reg_394 <= 13'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        row_ind_V_0_reg_382 <= row_ind_V_1_1_reg_371;
    end else if (((icmp_ln878_2_fu_662_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        row_ind_V_0_reg_382 <= row_ind_V_0_0_load_reg_1072;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        row_ind_V_1_1_reg_371 <= row_ind_V_2_reg_361;
    end else if (((icmp_ln878_2_fu_662_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        row_ind_V_1_1_reg_371 <= row_ind_V_1_0_load_reg_1077;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln259_fu_573_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        row_ind_V_1_reg_327 <= init_row_ind_fu_558_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        row_ind_V_1_reg_327 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        row_ind_V_2_reg_361 <= row_ind_V_0_reg_382;
    end else if (((icmp_ln878_2_fu_662_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        row_ind_V_2_reg_361 <= row_ind_V_2_0_load_reg_1082;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter5 == 1'b1) & (icmp_ln878_4_reg_1193_pp3_iter4_reg == 1'd1))) begin
        src_buf_V_0_0_reg_430 <= src_buf_V_0_1_reg_1235;
    end else if (((icmp_ln878_3_fu_721_p2 == 1'd1) & (icmp_ln878_2_reg_1117 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        src_buf_V_0_0_reg_430 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter6 == 1'b1) & (icmp_ln878_4_reg_1193_pp3_iter5_reg == 1'd1))) begin
        src_buf_V_1_0_reg_465 <= src_buf_V_1_1_reg_1247;
    end else if (((icmp_ln878_3_fu_721_p2 == 1'd1) & (icmp_ln878_2_reg_1117 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        src_buf_V_1_0_reg_465 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp3_iter7 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln878_4_reg_1193_pp3_iter6_reg == 1'd1))) begin
        src_buf_V_2_0_reg_511 <= src_buf_V_2_1_reg_1264;
    end else if (((icmp_ln878_3_fu_721_p2 == 1'd1) & (icmp_ln878_2_reg_1117 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        src_buf_V_2_0_reg_511 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        add_ln1616_reg_1112 <= add_ln1616_fu_647_p2;
        icmp_ln878_2_reg_1117 <= icmp_ln878_2_fu_662_p2;
        op2_assign_reg_1107 <= op2_assign_fu_641_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        add_ln691_reg_1090 <= add_ln691_fu_598_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        ap_phi_reg_pp3_iter2_buf_cop_V_0_0_reg_454 <= ap_phi_reg_pp3_iter1_buf_cop_V_0_0_reg_454;
        ap_phi_reg_pp3_iter2_buf_cop_V_1_reg_489 <= ap_phi_reg_pp3_iter1_buf_cop_V_1_reg_489;
        ap_phi_reg_pp3_iter2_buf_cop_V_2_reg_524 <= ap_phi_reg_pp3_iter1_buf_cop_V_2_reg_524;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter2 == 1'b1))) begin
        ap_phi_reg_pp3_iter3_arrayidx396_i179246_load_0_2_reg_418 <= ap_phi_reg_pp3_iter2_arrayidx396_i179246_load_0_2_reg_418;
        ap_phi_reg_pp3_iter3_buf_cop_V_0_0_reg_454 <= ap_phi_reg_pp3_iter2_buf_cop_V_0_0_reg_454;
        ap_phi_reg_pp3_iter3_buf_cop_V_1_reg_489 <= ap_phi_reg_pp3_iter2_buf_cop_V_1_reg_489;
        ap_phi_reg_pp3_iter3_buf_cop_V_2_reg_524 <= ap_phi_reg_pp3_iter2_buf_cop_V_2_reg_524;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter4 == 1'b1))) begin
        ap_phi_reg_pp3_iter5_buf_cop_V_1_reg_489 <= ap_phi_reg_pp3_iter4_buf_cop_V_1_reg_489;
        ap_phi_reg_pp3_iter5_buf_cop_V_2_reg_524 <= ap_phi_reg_pp3_iter4_buf_cop_V_2_reg_524;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter5 == 1'b1))) begin
        ap_phi_reg_pp3_iter6_buf_cop_V_2_reg_524 <= ap_phi_reg_pp3_iter5_buf_cop_V_2_reg_524;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln878_3_fu_721_p2 == 1'd1) & (icmp_ln878_2_reg_1117 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        cmp_i_i115_i_reg_1170 <= cmp_i_i115_i_fu_726_p2;
        trunc_ln123_reg_1174 <= trunc_ln123_fu_731_p1;
        trunc_ln136_1_reg_1183 <= trunc_ln136_1_fu_739_p1;
        trunc_ln136_reg_1178 <= trunc_ln136_fu_735_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        col_V_1_reg_1188 <= col_V_1_fu_743_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        col_V_reg_406_pp3_iter1_reg <= col_V_reg_406;
        icmp_ln878_4_reg_1193 <= icmp_ln878_4_fu_757_p2;
        icmp_ln878_4_reg_1193_pp3_iter1_reg <= icmp_ln878_4_reg_1193;
        icmp_ln878_5_reg_1197_pp3_iter1_reg <= icmp_ln878_5_reg_1197;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        empty_reg_1062 <= empty_fu_554_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp3_stage0_11001)) begin
        icmp_ln878_4_reg_1193_pp3_iter2_reg <= icmp_ln878_4_reg_1193_pp3_iter1_reg;
        icmp_ln878_4_reg_1193_pp3_iter3_reg <= icmp_ln878_4_reg_1193_pp3_iter2_reg;
        icmp_ln878_4_reg_1193_pp3_iter4_reg <= icmp_ln878_4_reg_1193_pp3_iter3_reg;
        icmp_ln878_4_reg_1193_pp3_iter5_reg <= icmp_ln878_4_reg_1193_pp3_iter4_reg;
        icmp_ln878_4_reg_1193_pp3_iter6_reg <= icmp_ln878_4_reg_1193_pp3_iter5_reg;
        icmp_ln878_5_reg_1197_pp3_iter2_reg <= icmp_ln878_5_reg_1197_pp3_iter1_reg;
        icmp_ln882_reg_1221_pp3_iter3_reg <= icmp_ln882_reg_1221;
        icmp_ln882_reg_1221_pp3_iter4_reg <= icmp_ln882_reg_1221_pp3_iter3_reg;
        icmp_ln882_reg_1221_pp3_iter5_reg <= icmp_ln882_reg_1221_pp3_iter4_reg;
        icmp_ln882_reg_1221_pp3_iter6_reg <= icmp_ln882_reg_1221_pp3_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln878_4_fu_757_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        icmp_ln878_5_reg_1197 <= icmp_ln878_5_fu_762_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        icmp_ln878_reg_1095 <= icmp_ln878_fu_608_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln878_4_reg_1193_pp3_iter1_reg == 1'd1))) begin
        icmp_ln882_reg_1221 <= icmp_ln882_fu_788_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln878_4_reg_1193_pp3_iter4_reg == 1'd1) & (tobool_i_i_1_2_reg_1146 == 1'd0))) begin
        icmp_ln886_4_reg_1259 <= icmp_ln886_4_fu_904_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln878_4_reg_1193_pp3_iter3_reg == 1'd1))) begin
        max_V_2_reg_1240 <= max_V_2_fu_858_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln878_4_reg_1193_pp3_iter4_reg == 1'd1))) begin
        max_V_4_reg_1253 <= max_V_4_fu_897_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln878_4_reg_1193_pp3_iter5_reg == 1'd1))) begin
        max_V_7_reg_1271 <= max_V_7_fu_956_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln259_fu_573_p2 == 1'd0) & (ap_phi_mux_row_ind_V_1_phi_fu_331_p4 == 2'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        row_ind_V_0_0_fu_114[1 : 0] <= zext_ln301_fu_579_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        row_ind_V_0_0_load_reg_1072[1 : 0] <= row_ind_V_0_0_fu_114[1 : 0];
        row_ind_V_1_0_load_reg_1077[1 : 0] <= row_ind_V_1_0_fu_118[1 : 0];
        row_ind_V_2_0_load_reg_1082[1 : 0] <= row_ind_V_2_0_fu_122[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln259_fu_573_p2 == 1'd0) & (ap_phi_mux_row_ind_V_1_phi_fu_331_p4 == 2'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        row_ind_V_1_0_fu_118[1 : 0] <= zext_ln301_fu_579_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((~(ap_phi_mux_row_ind_V_1_phi_fu_331_p4 == 2'd1) & ~(ap_phi_mux_row_ind_V_1_phi_fu_331_p4 == 2'd0) & (icmp_ln259_fu_573_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        row_ind_V_2_0_fu_122[1 : 0] <= zext_ln301_fu_579_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter4 == 1'b1) & (icmp_ln878_4_reg_1193_pp3_iter3_reg == 1'd1))) begin
        src_buf_V_0_1_reg_1235 <= src_buf_V_0_1_xfExtractPixels_1_1_0_s_fu_536_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter5 == 1'b1) & (icmp_ln878_4_reg_1193_pp3_iter4_reg == 1'd1))) begin
        src_buf_V_1_1_reg_1247 <= src_buf_V_1_1_xfExtractPixels_1_1_0_s_fu_542_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter6 == 1'b1) & (icmp_ln878_4_reg_1193_pp3_iter5_reg == 1'd1))) begin
        src_buf_V_2_1_reg_1264 <= src_buf_V_2_1_xfExtractPixels_1_1_0_s_fu_548_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln878_2_fu_662_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        tobool_i_i_160_reg_1126 <= tobool_i_i_160_fu_673_p2;
        tobool_i_i_1_1_reg_1141 <= tobool_i_i_1_1_fu_688_p2;
        tobool_i_i_1_2_reg_1146 <= tobool_i_i_1_2_fu_693_p2;
        tobool_i_i_1_reg_1136 <= tobool_i_i_1_fu_683_p2;
        tobool_i_i_269_reg_1131 <= tobool_i_i_269_fu_678_p2;
        tobool_i_i_2_1_reg_1156 <= tobool_i_i_2_1_fu_703_p2;
        tobool_i_i_2_2_reg_1161 <= tobool_i_i_2_2_fu_708_p2;
        tobool_i_i_2_reg_1151 <= tobool_i_i_2_fu_698_p2;
        tobool_i_i_reg_1121 <= tobool_i_i_fu_668_p2;
    end
end

always @ (*) begin
    if ((icmp_ln878_fu_608_p2 == 1'd0)) begin
        ap_condition_pp1_exit_iter0_state4 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state4 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter6 == 1'b1) & (ap_enable_reg_pp3_iter5 == 1'b0))) begin
        ap_condition_pp3_exit_iter6_state16 = 1'b1;
    end else begin
        ap_condition_pp3_exit_iter6_state16 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0_subdone) & (icmp_ln878_4_fu_757_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        ap_condition_pp3_flush_enable = 1'b1;
    end else begin
        ap_condition_pp3_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((1'b1 == ap_CS_fsm_state9) & ((icmp_ln878_3_fu_721_p2 == 1'd0) | (icmp_ln878_2_reg_1117 == 1'd1))))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter7 == 1'b0) & (ap_enable_reg_pp3_iter1 == 1'b0) & (ap_enable_reg_pp3_iter3 == 1'b0) & (ap_enable_reg_pp3_iter2 == 1'b0) & (ap_enable_reg_pp3_iter6 == 1'b0) & (ap_enable_reg_pp3_iter5 == 1'b0) & (ap_enable_reg_pp3_iter4 == 1'b0) & (ap_enable_reg_pp3_iter0 == 1'b0))) begin
        ap_idle_pp3 = 1'b1;
    end else begin
        ap_idle_pp3 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln878_4_reg_1193 == 1'd1) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        ap_phi_mux_col_V_phi_fu_410_p4 = col_V_1_reg_1188;
    end else begin
        ap_phi_mux_col_V_phi_fu_410_p4 = col_V_reg_406;
    end
end

always @ (*) begin
    if (((icmp_ln878_reg_1095 == 1'd1) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_i_col_046_0_phi_fu_342_p4 = add_ln691_reg_1090;
    end else begin
        ap_phi_mux_i_col_046_0_phi_fu_342_p4 = i_col_046_0_reg_338;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter6 == 1'b1) & (icmp_ln878_4_reg_1193_pp3_iter5_reg == 1'd1))) begin
        ap_phi_mux_p_Val2_1_phi_fu_481_p4 = src_buf_V_1_0_reg_465;
    end else begin
        ap_phi_mux_p_Val2_1_phi_fu_481_p4 = p_Val2_1_reg_477;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter7 == 1'b1) & (1'b0 == ap_block_pp3_stage0) & (icmp_ln878_4_reg_1193_pp3_iter6_reg == 1'd1))) begin
        ap_phi_mux_p_Val2_2_phi_fu_504_p4 = src_buf_V_2_0_reg_511;
    end else begin
        ap_phi_mux_p_Val2_2_phi_fu_504_p4 = p_Val2_2_reg_500;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter5 == 1'b1) & (icmp_ln878_4_reg_1193_pp3_iter4_reg == 1'd1))) begin
        ap_phi_mux_p_Val2_s_phi_fu_446_p4 = src_buf_V_0_0_reg_430;
    end else begin
        ap_phi_mux_p_Val2_s_phi_fu_446_p4 = p_Val2_s_reg_442;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter5 == 1'b1) & (icmp_ln878_4_reg_1193_pp3_iter4_reg == 1'd1))) begin
        ap_phi_mux_src_buf_V_0_0_phi_fu_434_p4 = src_buf_V_0_1_reg_1235;
    end else begin
        ap_phi_mux_src_buf_V_0_0_phi_fu_434_p4 = src_buf_V_0_0_reg_430;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter6 == 1'b1) & (icmp_ln878_4_reg_1193_pp3_iter5_reg == 1'd1))) begin
        ap_phi_mux_src_buf_V_1_0_phi_fu_469_p4 = src_buf_V_1_1_reg_1247;
    end else begin
        ap_phi_mux_src_buf_V_1_0_phi_fu_469_p4 = src_buf_V_1_0_reg_465;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter7 == 1'b1) & (1'b0 == ap_block_pp3_stage0) & (icmp_ln878_4_reg_1193_pp3_iter6_reg == 1'd1))) begin
        ap_phi_mux_src_buf_V_2_0_phi_fu_516_p4 = src_buf_V_2_1_reg_1264;
    end else begin
        ap_phi_mux_src_buf_V_2_0_phi_fu_516_p4 = src_buf_V_2_0_reg_511;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & ((icmp_ln878_3_fu_721_p2 == 1'd0) | (icmp_ln878_2_reg_1117 == 1'd1)))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((cmp_i_i115_i_reg_1170 == 1'd1) & (icmp_ln878_5_reg_1197 == 1'd1) & (icmp_ln878_4_reg_1193 == 1'd1) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0) & (trunc_ln123_reg_1174 == 2'd0) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        buf_V_0_address1 = zext_ln534_2_fu_774_p1;
    end else if (((cmp_i_i115_i_reg_1170 == 1'd0) & (icmp_ln878_5_reg_1197 == 1'd1) & (icmp_ln878_4_reg_1193 == 1'd1) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0) & (trunc_ln123_reg_1174 == 2'd0) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        buf_V_0_address1 = zext_ln534_3_fu_767_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_0_address1 = zext_ln534_1_fu_633_p1;
    end else begin
        buf_V_0_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter2 == 1'b1))) begin
        buf_V_0_ce0 = 1'b1;
    end else begin
        buf_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((cmp_i_i115_i_reg_1170 == 1'd1) & (icmp_ln878_5_reg_1197 == 1'd1) & (icmp_ln878_4_reg_1193 == 1'd1) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (trunc_ln123_reg_1174 == 2'd0) & (1'b1 == ap_CS_fsm_pp3_stage0)) | ((cmp_i_i115_i_reg_1170 == 1'd0) & (icmp_ln878_5_reg_1197 == 1'd1) & (icmp_ln878_4_reg_1193 == 1'd1) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (trunc_ln123_reg_1174 == 2'd0) & (1'b1 == ap_CS_fsm_pp3_stage0)))) begin
        buf_V_0_ce1 = 1'b1;
    end else begin
        buf_V_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((cmp_i_i115_i_reg_1170 == 1'd1) & (icmp_ln878_5_reg_1197 == 1'd1) & (icmp_ln878_4_reg_1193 == 1'd1) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0) & (trunc_ln123_reg_1174 == 2'd0) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        buf_V_0_d1 = in_mat_419_dout;
    end else if (((1'b1 == ap_CS_fsm_state7) | ((cmp_i_i115_i_reg_1170 == 1'd0) & (icmp_ln878_5_reg_1197 == 1'd1) & (icmp_ln878_4_reg_1193 == 1'd1) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0) & (trunc_ln123_reg_1174 == 2'd0) & (1'b1 == ap_CS_fsm_pp3_stage0)))) begin
        buf_V_0_d1 = 8'd0;
    end else begin
        buf_V_0_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((cmp_i_i115_i_reg_1170 == 1'd1) & (icmp_ln878_5_reg_1197 == 1'd1) & (icmp_ln878_4_reg_1193 == 1'd1) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (trunc_ln123_reg_1174 == 2'd0) & (1'b1 == ap_CS_fsm_pp3_stage0)) | ((cmp_i_i115_i_reg_1170 == 1'd0) & (icmp_ln878_5_reg_1197 == 1'd1) & (icmp_ln878_4_reg_1193 == 1'd1) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (trunc_ln123_reg_1174 == 2'd0) & (1'b1 == ap_CS_fsm_pp3_stage0)) | ((icmp_ln878_1_fu_628_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_V_0_we1 = 1'b1;
    end else begin
        buf_V_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((cmp_i_i115_i_reg_1170 == 1'd1) & (icmp_ln878_5_reg_1197 == 1'd1) & (icmp_ln878_4_reg_1193 == 1'd1) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0) & (trunc_ln123_reg_1174 == 2'd1) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        buf_V_1_address1 = zext_ln534_2_fu_774_p1;
    end else if (((cmp_i_i115_i_reg_1170 == 1'd0) & (icmp_ln878_5_reg_1197 == 1'd1) & (icmp_ln878_4_reg_1193 == 1'd1) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0) & (trunc_ln123_reg_1174 == 2'd1) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        buf_V_1_address1 = zext_ln534_3_fu_767_p1;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        buf_V_1_address1 = zext_ln534_fu_613_p1;
    end else begin
        buf_V_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter2 == 1'b1))) begin
        buf_V_1_ce0 = 1'b1;
    end else begin
        buf_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((cmp_i_i115_i_reg_1170 == 1'd1) & (icmp_ln878_5_reg_1197 == 1'd1) & (icmp_ln878_4_reg_1193 == 1'd1) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (trunc_ln123_reg_1174 == 2'd1) & (1'b1 == ap_CS_fsm_pp3_stage0)) | ((cmp_i_i115_i_reg_1170 == 1'd0) & (icmp_ln878_5_reg_1197 == 1'd1) & (icmp_ln878_4_reg_1193 == 1'd1) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (trunc_ln123_reg_1174 == 2'd1) & (1'b1 == ap_CS_fsm_pp3_stage0)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
        buf_V_1_ce1 = 1'b1;
    end else begin
        buf_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((cmp_i_i115_i_reg_1170 == 1'd0) & (icmp_ln878_5_reg_1197 == 1'd1) & (icmp_ln878_4_reg_1193 == 1'd1) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0) & (trunc_ln123_reg_1174 == 2'd1) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        buf_V_1_d1 = 8'd0;
    end else if ((((cmp_i_i115_i_reg_1170 == 1'd1) & (icmp_ln878_5_reg_1197 == 1'd1) & (icmp_ln878_4_reg_1193 == 1'd1) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0) & (trunc_ln123_reg_1174 == 2'd1) & (1'b1 == ap_CS_fsm_pp3_stage0)) | ((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
        buf_V_1_d1 = in_mat_419_dout;
    end else begin
        buf_V_1_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((cmp_i_i115_i_reg_1170 == 1'd1) & (icmp_ln878_5_reg_1197 == 1'd1) & (icmp_ln878_4_reg_1193 == 1'd1) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (trunc_ln123_reg_1174 == 2'd1) & (1'b1 == ap_CS_fsm_pp3_stage0)) | ((icmp_ln878_reg_1095 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((cmp_i_i115_i_reg_1170 == 1'd0) & (icmp_ln878_5_reg_1197 == 1'd1) & (icmp_ln878_4_reg_1193 == 1'd1) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (trunc_ln123_reg_1174 == 2'd1) & (1'b1 == ap_CS_fsm_pp3_stage0)))) begin
        buf_V_1_we1 = 1'b1;
    end else begin
        buf_V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_950)) begin
        if ((cmp_i_i115_i_reg_1170 == 1'd1)) begin
            buf_V_2_address1 = zext_ln534_2_fu_774_p1;
        end else if ((cmp_i_i115_i_reg_1170 == 1'd0)) begin
            buf_V_2_address1 = zext_ln534_3_fu_767_p1;
        end else begin
            buf_V_2_address1 = 'bx;
        end
    end else begin
        buf_V_2_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter2 == 1'b1))) begin
        buf_V_2_ce0 = 1'b1;
    end else begin
        buf_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(trunc_ln123_reg_1174 == 2'd0) & ~(trunc_ln123_reg_1174 == 2'd1) & (cmp_i_i115_i_reg_1170 == 1'd1) & (icmp_ln878_5_reg_1197 == 1'd1) & (icmp_ln878_4_reg_1193 == 1'd1) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0)) | (~(trunc_ln123_reg_1174 == 2'd0) & ~(trunc_ln123_reg_1174 == 2'd1) & (cmp_i_i115_i_reg_1170 == 1'd0) & (icmp_ln878_5_reg_1197 == 1'd1) & (icmp_ln878_4_reg_1193 == 1'd1) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0)))) begin
        buf_V_2_ce1 = 1'b1;
    end else begin
        buf_V_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_950)) begin
        if ((cmp_i_i115_i_reg_1170 == 1'd1)) begin
            buf_V_2_d1 = in_mat_419_dout;
        end else if ((cmp_i_i115_i_reg_1170 == 1'd0)) begin
            buf_V_2_d1 = 8'd0;
        end else begin
            buf_V_2_d1 = 'bx;
        end
    end else begin
        buf_V_2_d1 = 'bx;
    end
end

always @ (*) begin
    if (((~(trunc_ln123_reg_1174 == 2'd0) & ~(trunc_ln123_reg_1174 == 2'd1) & (cmp_i_i115_i_reg_1170 == 1'd1) & (icmp_ln878_5_reg_1197 == 1'd1) & (icmp_ln878_4_reg_1193 == 1'd1) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0)) | (~(trunc_ln123_reg_1174 == 2'd0) & ~(trunc_ln123_reg_1174 == 2'd1) & (cmp_i_i115_i_reg_1170 == 1'd0) & (icmp_ln878_5_reg_1197 == 1'd1) & (icmp_ln878_4_reg_1193 == 1'd1) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0)))) begin
        buf_V_2_we1 = 1'b1;
    end else begin
        buf_V_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((cmp_i_i115_i_reg_1170 == 1'd1) & (icmp_ln878_5_reg_1197 == 1'd1) & (icmp_ln878_4_reg_1193 == 1'd1) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0) & (1'b1 == ap_CS_fsm_pp3_stage0)) | ((icmp_ln878_reg_1095 == 1'd1) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
        in_mat_419_blk_n = in_mat_419_empty_n;
    end else begin
        in_mat_419_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0) & (ap_predicate_op146_read_state11 == 1'b1)) | ((icmp_ln878_reg_1095 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
        in_mat_419_read = 1'b1;
    end else begin
        in_mat_419_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln882_reg_1221_pp3_iter6_reg == 1'd0) & (ap_enable_reg_pp3_iter7 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        out_mat_420_blk_n = out_mat_420_full_n;
    end else begin
        out_mat_420_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln882_reg_1221_pp3_iter6_reg == 1'd0) & (ap_enable_reg_pp3_iter7 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001))) begin
        out_mat_420_write = 1'b1;
    end else begin
        out_mat_420_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln259_fu_573_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if (~((1'b0 == ap_block_pp1_stage0_subdone) & (icmp_ln878_fu_608_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((1'b0 == ap_block_pp1_stage0_subdone) & (icmp_ln878_fu_608_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((icmp_ln878_1_fu_628_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & ((icmp_ln878_3_fu_721_p2 == 1'd0) | (icmp_ln878_2_reg_1117 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end
        end
        ap_ST_fsm_pp3_stage0 : begin
            if (~((1'b0 == ap_block_pp3_stage0_subdone) & (ap_enable_reg_pp3_iter6 == 1'b1) & (ap_enable_reg_pp3_iter5 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end else if (((1'b0 == ap_block_pp3_stage0_subdone) & (ap_enable_reg_pp3_iter6 == 1'b1) & (ap_enable_reg_pp3_iter5 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1616_fu_647_p2 = (empty_reg_1062 + 14'd1);

assign add_ln691_1_fu_618_p2 = (i_col_V_0_reg_350 + 13'd1);

assign add_ln691_fu_598_p2 = (ap_phi_mux_i_col_046_0_phi_fu_342_p4 + 13'd1);

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp3_stage0 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd7];

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_11001 = ((icmp_ln878_reg_1095 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (in_mat_419_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_pp1_stage0_subdone = ((icmp_ln878_reg_1095 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (in_mat_419_empty_n == 1'b0));
end

assign ap_block_pp3_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp3_stage0_01001 = (((icmp_ln882_reg_1221_pp3_iter6_reg == 1'd0) & (ap_enable_reg_pp3_iter7 == 1'b1) & (out_mat_420_full_n == 1'b0)) | ((ap_enable_reg_pp3_iter1 == 1'b1) & (in_mat_419_empty_n == 1'b0) & (ap_predicate_op146_read_state11 == 1'b1)));
end

always @ (*) begin
    ap_block_pp3_stage0_11001 = (((icmp_ln882_reg_1221_pp3_iter6_reg == 1'd0) & (ap_enable_reg_pp3_iter7 == 1'b1) & (out_mat_420_full_n == 1'b0)) | ((ap_enable_reg_pp3_iter1 == 1'b1) & (in_mat_419_empty_n == 1'b0) & (ap_predicate_op146_read_state11 == 1'b1)));
end

always @ (*) begin
    ap_block_pp3_stage0_subdone = (((icmp_ln882_reg_1221_pp3_iter6_reg == 1'd0) & (ap_enable_reg_pp3_iter7 == 1'b1) & (out_mat_420_full_n == 1'b0)) | ((ap_enable_reg_pp3_iter1 == 1'b1) & (in_mat_419_empty_n == 1'b0) & (ap_predicate_op146_read_state11 == 1'b1)));
end

assign ap_block_state10_pp3_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state11_pp3_stage0_iter1 = ((in_mat_419_empty_n == 1'b0) & (ap_predicate_op146_read_state11 == 1'b1));
end

assign ap_block_state12_pp3_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp3_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp3_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp3_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp3_stage0_iter6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state17_pp3_stage0_iter7 = ((icmp_ln882_reg_1221_pp3_iter6_reg == 1'd0) & (out_mat_420_full_n == 1'b0));
end

assign ap_block_state4_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp1_stage0_iter1 = ((icmp_ln878_reg_1095 == 1'd1) & (in_mat_419_empty_n == 1'b0));
end

always @ (*) begin
    ap_condition_258 = ((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0));
end

always @ (*) begin
    ap_condition_279 = ((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0));
end

always @ (*) begin
    ap_condition_486 = ((cmp_i_i115_i_reg_1170 == 1'd0) & (icmp_ln878_5_fu_762_p2 == 1'd1) & (icmp_ln878_4_fu_757_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_86 = ((cmp_i_i115_i_reg_1170 == 1'd1) & (icmp_ln878_5_reg_1197 == 1'd1) & (icmp_ln878_4_reg_1193 == 1'd1));
end

always @ (*) begin
    ap_condition_950 = (~(trunc_ln123_reg_1174 == 2'd0) & ~(trunc_ln123_reg_1174 == 2'd1) & (icmp_ln878_5_reg_1197 == 1'd1) & (icmp_ln878_4_reg_1193 == 1'd1) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0) & (1'b1 == ap_CS_fsm_pp3_stage0));
end

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_enable_pp3 = (ap_idle_pp3 ^ 1'b1);

assign ap_phi_mux_row_ind_V_1_phi_fu_331_p4 = row_ind_V_1_reg_327;

assign ap_phi_reg_pp3_iter0_arrayidx396_i179246_load_0_2_reg_418 = 'bx;

assign ap_phi_reg_pp3_iter0_buf_cop_V_0_0_reg_454 = 'bx;

assign ap_phi_reg_pp3_iter0_buf_cop_V_1_reg_489 = 'bx;

assign ap_phi_reg_pp3_iter0_buf_cop_V_2_reg_524 = 'bx;

always @ (*) begin
    ap_predicate_op146_read_state11 = ((cmp_i_i115_i_reg_1170 == 1'd1) & (icmp_ln878_5_reg_1197 == 1'd1) & (icmp_ln878_4_reg_1193 == 1'd1));
end

assign buf_V_0_address0 = zext_ln1616_fu_781_p1;

assign buf_V_1_address0 = zext_ln1616_fu_781_p1;

assign buf_V_2_address0 = zext_ln1616_fu_781_p1;

assign cmp_i_i115_i_fu_726_p2 = ((zext_ln878_2_fu_713_p1 < img_height) ? 1'b1 : 1'b0);

assign col_V_1_fu_743_p2 = (ap_phi_mux_col_V_phi_fu_410_p4 + 13'd1);

assign empty_fu_554_p1 = img_width[13:0];

assign icmp_ln259_fu_573_p2 = ((row_ind_V_1_reg_327 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln878_1_fu_628_p2 = ((zext_ln878_1_fu_624_p1 < img_width) ? 1'b1 : 1'b0);

assign icmp_ln878_2_fu_662_p2 = ((tmp_1_fu_652_p4 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln878_3_fu_721_p2 = ((zext_ln878_3_fu_717_p1 < op2_assign_reg_1107) ? 1'b1 : 1'b0);

assign icmp_ln878_4_fu_757_p2 = ((zext_ln878_5_fu_753_p1 < add_ln1616_reg_1112) ? 1'b1 : 1'b0);

assign icmp_ln878_5_fu_762_p2 = ((zext_ln878_4_fu_749_p1 < img_width) ? 1'b1 : 1'b0);

assign icmp_ln878_fu_608_p2 = ((zext_ln878_fu_604_p1 < img_width) ? 1'b1 : 1'b0);

assign icmp_ln882_fu_788_p2 = ((col_V_reg_406_pp3_iter1_reg == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln886_1_fu_844_p2 = ((src_buf_V_0_1_xfExtractPixels_1_1_0_s_fu_536_ap_return > max_V_1_fu_837_p3) ? 1'b1 : 1'b0);

assign icmp_ln886_2_fu_865_p2 = ((ap_phi_mux_p_Val2_1_phi_fu_481_p4 > max_V_2_reg_1240) ? 1'b1 : 1'b0);

assign icmp_ln886_3_fu_883_p2 = ((ap_phi_mux_src_buf_V_1_0_phi_fu_469_p4 > max_V_3_fu_877_p3) ? 1'b1 : 1'b0);

assign icmp_ln886_4_fu_904_p2 = ((src_buf_V_1_1_xfExtractPixels_1_1_0_s_fu_542_ap_return > max_V_4_fu_897_p3) ? 1'b1 : 1'b0);

assign icmp_ln886_5_fu_921_p2 = ((ap_phi_mux_p_Val2_2_phi_fu_504_p4 > max_V_5_fu_915_p3) ? 1'b1 : 1'b0);

assign icmp_ln886_6_fu_942_p2 = ((ap_phi_mux_src_buf_V_2_0_phi_fu_516_p4 > max_V_6_fu_935_p3) ? 1'b1 : 1'b0);

assign icmp_ln886_7_fu_963_p2 = ((src_buf_V_2_1_reg_1264 > max_V_7_reg_1271) ? 1'b1 : 1'b0);

assign icmp_ln886_fu_823_p2 = ((ap_phi_mux_src_buf_V_0_0_phi_fu_434_p4 > ret_fu_816_p3) ? 1'b1 : 1'b0);

assign img_height_cast_fu_638_p1 = img_height;

assign init_row_ind_fu_558_p2 = (row_ind_V_1_reg_327 + 2'd1);

assign max_V_1_fu_837_p3 = ((tobool_i_i_160_reg_1126[0:0] == 1'b1) ? ret_fu_816_p3 : select_ln56_fu_829_p3);

assign max_V_2_fu_858_p3 = ((tobool_i_i_269_reg_1131[0:0] == 1'b1) ? max_V_1_fu_837_p3 : select_ln56_1_fu_850_p3);

assign max_V_3_fu_877_p3 = ((tobool_i_i_1_reg_1136[0:0] == 1'b1) ? max_V_2_reg_1240 : select_ln56_2_fu_870_p3);

assign max_V_4_fu_897_p3 = ((tobool_i_i_1_1_reg_1141[0:0] == 1'b1) ? max_V_3_fu_877_p3 : select_ln56_3_fu_889_p3);

assign max_V_5_fu_915_p3 = ((tobool_i_i_1_2_reg_1146[0:0] == 1'b1) ? max_V_4_reg_1253 : select_ln56_4_fu_910_p3);

assign max_V_6_fu_935_p3 = ((tobool_i_i_2_reg_1151[0:0] == 1'b1) ? max_V_5_fu_915_p3 : select_ln56_5_fu_927_p3);

assign max_V_7_fu_956_p3 = ((tobool_i_i_2_1_reg_1156[0:0] == 1'b1) ? max_V_6_fu_935_p3 : select_ln56_6_fu_948_p3);

assign op2_assign_fu_641_p2 = (img_height_cast_fu_638_p1 + 17'd1);

assign out_mat_420_din = ((tobool_i_i_2_2_reg_1161[0:0] == 1'b1) ? max_V_7_reg_1271 : select_ln56_7_fu_967_p3);

assign ret_fu_816_p3 = ((tobool_i_i_reg_1121[0:0] == 1'b1) ? 8'd0 : ap_phi_mux_p_Val2_s_phi_fu_446_p4);

assign row_V_1_fu_980_p2 = (row_V_reg_394 + 13'd1);

assign select_ln56_1_fu_850_p3 = ((icmp_ln886_1_fu_844_p2[0:0] == 1'b1) ? src_buf_V_0_1_xfExtractPixels_1_1_0_s_fu_536_ap_return : max_V_1_fu_837_p3);

assign select_ln56_2_fu_870_p3 = ((icmp_ln886_2_fu_865_p2[0:0] == 1'b1) ? ap_phi_mux_p_Val2_1_phi_fu_481_p4 : max_V_2_reg_1240);

assign select_ln56_3_fu_889_p3 = ((icmp_ln886_3_fu_883_p2[0:0] == 1'b1) ? ap_phi_mux_src_buf_V_1_0_phi_fu_469_p4 : max_V_3_fu_877_p3);

assign select_ln56_4_fu_910_p3 = ((icmp_ln886_4_reg_1259[0:0] == 1'b1) ? src_buf_V_1_1_reg_1247 : max_V_4_reg_1253);

assign select_ln56_5_fu_927_p3 = ((icmp_ln886_5_fu_921_p2[0:0] == 1'b1) ? ap_phi_mux_p_Val2_2_phi_fu_504_p4 : max_V_5_fu_915_p3);

assign select_ln56_6_fu_948_p3 = ((icmp_ln886_6_fu_942_p2[0:0] == 1'b1) ? ap_phi_mux_src_buf_V_2_0_phi_fu_516_p4 : max_V_6_fu_935_p3);

assign select_ln56_7_fu_967_p3 = ((icmp_ln886_7_fu_963_p2[0:0] == 1'b1) ? src_buf_V_2_1_reg_1264 : max_V_7_reg_1271);

assign select_ln56_fu_829_p3 = ((icmp_ln886_fu_823_p2[0:0] == 1'b1) ? ap_phi_mux_src_buf_V_0_0_phi_fu_434_p4 : ret_fu_816_p3);

assign tmp_1_fu_652_p4 = {{op2_assign_fu_641_p2[16:1]}};

assign tobool_i_i_160_fu_673_p2 = ((p_read1 == 8'd0) ? 1'b1 : 1'b0);

assign tobool_i_i_1_1_fu_688_p2 = ((p_read4 == 8'd0) ? 1'b1 : 1'b0);

assign tobool_i_i_1_2_fu_693_p2 = ((p_read5 == 8'd0) ? 1'b1 : 1'b0);

assign tobool_i_i_1_fu_683_p2 = ((p_read3 == 8'd0) ? 1'b1 : 1'b0);

assign tobool_i_i_269_fu_678_p2 = ((p_read2 == 8'd0) ? 1'b1 : 1'b0);

assign tobool_i_i_2_1_fu_703_p2 = ((p_read7 == 8'd0) ? 1'b1 : 1'b0);

assign tobool_i_i_2_2_fu_708_p2 = ((p_read8 == 8'd0) ? 1'b1 : 1'b0);

assign tobool_i_i_2_fu_698_p2 = ((p_read6 == 8'd0) ? 1'b1 : 1'b0);

assign tobool_i_i_fu_668_p2 = ((p_read == 8'd0) ? 1'b1 : 1'b0);

assign trunc_ln123_fu_731_p1 = row_ind_V_2_reg_361[1:0];

assign trunc_ln136_1_fu_739_p1 = row_ind_V_1_1_reg_371[1:0];

assign trunc_ln136_fu_735_p1 = row_ind_V_0_reg_382[1:0];

assign zext_ln1616_fu_781_p1 = col_V_reg_406_pp3_iter1_reg;

assign zext_ln301_fu_579_p1 = row_ind_V_1_reg_327;

assign zext_ln534_1_fu_633_p1 = i_col_V_0_reg_350;

assign zext_ln534_2_fu_774_p1 = col_V_reg_406;

assign zext_ln534_3_fu_767_p1 = col_V_reg_406;

assign zext_ln534_fu_613_p1 = i_col_046_0_reg_338;

assign zext_ln878_1_fu_624_p1 = i_col_V_0_reg_350;

assign zext_ln878_2_fu_713_p1 = row_V_reg_394;

assign zext_ln878_3_fu_717_p1 = row_V_reg_394;

assign zext_ln878_4_fu_749_p1 = ap_phi_mux_col_V_phi_fu_410_p4;

assign zext_ln878_5_fu_753_p1 = ap_phi_mux_col_V_phi_fu_410_p4;

assign zext_ln878_fu_604_p1 = ap_phi_mux_i_col_046_0_phi_fu_342_p4;

always @ (posedge ap_clk) begin
    row_ind_V_0_0_load_reg_1072[12:2] <= 11'b00000000000;
    row_ind_V_1_0_load_reg_1077[12:2] <= 11'b00000000000;
    row_ind_V_2_0_load_reg_1082[12:2] <= 11'b00000000000;
    row_ind_V_0_0_fu_114[12:2] <= 11'b00000000000;
    row_ind_V_1_0_fu_118[12:2] <= 11'b00000000000;
    row_ind_V_2_0_fu_122[12:2] <= 11'b00000000000;
end

endmodule //dilation_accel_xfdilate_32_32_1_0_1_0_33_3_3_s
